### ISSUE TITLE
[ENH] Add condition time tracking

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#1]
Track when a condition is added to a combatant and how many turns remain until it expires.

**Comment by shaun-newsome** [comment]
Could a message either be displayed in chat or as a UI notification to list the active conditions on the combatant and how many turns remain?

As a GM I always forget which conditions are active so a reminder would be very useful!

**Comment by eclarke12** [comment]
> Could a message either be displayed in chat or as a UI notification to list the active conditions on the combatant and how many turns remain?
> 
> As a GM I always forget which conditions are active so a reminder would be very useful!

Yes you've read my mind. I also need that when I GM!

**Comment by eclarke12** [comment]
This could also be extended to include tracking of how many instances of a condition exist for systems like PF2e

**Comment by eclarke12** [comment]
Considering this delivered with Active Effects support. Will reopen if additional work is required
