### ISSUE TITLE
Movement prediction

### ISSUE THREAD

**Issue by ariakas2008** [death-save/combat-utility-belt#102]
When combat is started, change the way token movement is managed. When clic and dragging a token, the movement shows its calculated movement path, exactly like it works now when you clic and hold ctrl.
When you drop it, the token is moved without animation. Pressing ctrl pins waypoint.
See this video: https://youtu.be/Ox6ym2aaHGE?list=PLD4i-ngGs9thEXoHaxzRqD0b3zWcmpAOn&t=51

**Comment by eclarke12** [comment]
@ariakas2008 I think this is covered by other modules now?

**Comment by ariakas2008** [comment]
> @ariakas2008 I think this is covered by other modules now?

Yup, Show Drag  Distance. You can close ty!

**Comment by eclarke12** [comment]
Sorry I never got this done, glad it's been taken care of by someone else!
