### ISSUE TITLE
Support for Beaten condition (25% of max HP)

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#109]
Hello, I am the author of Grit and Glory, a realism-focused supplement for 5E, available here: https://www.gmbinder.com/share/-LDHolQY2FURKf-8xCT3

A popular rule in G&G and some other homebrew focused on realism that I am incorporating is having another threshold for a Beaten condition, at below 25% of max hp. Can you please consider adding another condition for Beaten that overwrites Bloodied when hp is under 25% of max hp? 

And while at it, can you please consider making the Bloodied icon red to be easily recognizable compared to the usual (typically white except for CUB) conditions? That would much help it being recognizable especially on Combat Tracker. 

Thanks in advance!

**Comment by eclarke12** [comment]
@apoapostolov can you confirm that Beaten is in *addition* to the existing bloodied/injured marking? That is you'd like a 2nd threshold of 25% that sets a new marker and removes the old one?

**Comment by apoapostolov** [comment]
@eclarke12 I am fine with either way you implement it but ideally, it should be an exclusive state that removes the Bloodied condition and adds Beaten condition.

**Comment by apoapostolov** [comment]
I am closing this as this is now supported by the fully customizable trigger system. I managed to reproduce it with great ease. 

![image](https://user-images.githubusercontent.com/4083812/80303951-f8248b00-87bb-11ea-94d8-f9dce76060c3.png)

**Comment by eclarke12** [comment]
@apoapostolov one note for those triggers: any trigger that fires when health is reduce should be checked to confirm whether it should include when health is 0. generally for "bloodied" type conditions you won't want it to fire on 0. in Triggler you can use the "Not on 0" option to ensure this behaviour
