### ISSUE TITLE
Adding Temporary Opponents is very poor process

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#112]
I had an impromptu combat today I had to add 5-6 temporary opponents and the process was very unintuitive and poor. I had to create them but then I had to add them to the map and had to manually add them to the combat tracker. Is there any chance this can be improved to automatically add them to the combat tracker without manually adding them to the map?

**Comment by eclarke12** [comment]
@apoapostolov there was a bug since 052 where temporary combatants weren't created correctly. This is solved in 1.0
