### ISSUE TITLE
[Feature Request] Ability to hide/unhide NPC names w/o going into settings

### ISSUE THREAD

**Issue by Valien** [death-save/combat-utility-belt#113]
CUB is pretty cool so far. Noticed while testing it out that the hid NPC names is great. I want my players to run checks to see if they know this creature they're about to fight.

So what I'd love to see is ability to unhide the name of the token/creature on an individual basis vs turning off the option in the game settings menu.

Say they are fighting a few diff mobs and they identify one of them but not the other creature. Maybe I can then unhide that specific creatures name so it shows in the combat tracker as the mob while the others would still be unknown.

Thoughts?

**Comment by eclarke12** [comment]
this was delivered in v1.2
