### ISSUE TITLE
PF2 Condition icons released by PF2 team

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#118]
Just bringing attention that PF2 FVTT team has a set of icons that could replace the WoW icons for improved visibility. Maybe cooperate to add them to CUB as well?

Based on:
https://old.reddit.com/r/Pathfinder2e/comments/g064bx/roll20_token_markers_pathfinder_2e_damage_types/
https://old.reddit.com/r/Pathfinder2e/comments/g19a98/roll20_token_markers_pathfinder_2e_conditions/

Available here: 
https://canary.discordapp.com/channels/170995199584108546/697845559435853865/700028389544951878

Previews:
https://canary.discordapp.com/channels/170995199584108546/697845559435853865/699984988044787802

Direct download: https://cdn.discordapp.com/attachments/697845559435853865/700028389163139092/02._Conditions.7z

**Comment by eclarke12** [comment]
pf2e will manage conditions within the system. users can still make custom mappings in Condition Lab but no CUB-default mapping will be provided at this point.
