### ISSUE TITLE
PF2 Conditions appear broken

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#120]
0.5.5, hosted on ForgeVTT. The PF2 icons do not render at all. 

![image](https://user-images.githubusercontent.com/4083812/79632462-06ddc300-8168-11ea-8b96-5c9a879e6681.png)

**Comment by ptapping** [comment]
The pf2e module updated their icons and the file names changed.
This pull request should fix them: #121

**Comment by eclarke12** [comment]
@apoapostolov condition tracking is/will be part of the pf2e system moving forward
