### ISSUE TITLE
CUB 1.0 Problem with Bloodied Logic.

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#128]
I have the following config for Bloodied condition behavior

![image](https://user-images.githubusercontent.com/4083812/80315758-51afa880-8802-11ea-8406-2bf2e46f48bc.png)

When the token is at max health say 36/36, removing 1 damage repeatedly from it causes the Bloodied condition to turn on, then turn off, then turn on, then turn off, etc.

**Comment by eclarke12** [comment]
This should be fixed with #136
