### ISSUE TITLE
[Award XP] pf1 character xp gets concatenated instead of added

### ISSUE THREAD

**Issue by EternalMana** [death-save/combat-utility-belt#142]
Using the pf1e system, I awarded 180 xp at the end of a fight to my PC who had 335 xp and they ended up with 335180 xp or so.
As shown on [this screenshot](https://cdn.discordapp.com/attachments/513918036919713802/706327320507449404/unknown.png)
I am currently running the latest pf1e version  (currently 0.411) and CUB 1.0.3

**Comment by eclarke12** [comment]
@EternalMana this issue seems to be resolved with Foundry 0.5.7, PF1 0.52 and CUB 1.0.3
let me know if you're still experiencing it
