### ISSUE TITLE
Add an option to always hide rolls

### ISSUE THREAD

**Issue by bsleys** [death-save/combat-utility-belt#143]
With Hide NPC Names and Hide Chat Card Footer both set. The following actions still expose the NPC name.

Reroll Initiative - each round the initiative rolls expose the existence of hidden NPC's in tracker. Hidden NPC's should have their initiative rolls hidden from players.

Auto Roll Hostile - when placing hostile npc's on the the map not only in their HP exposed to the players but also their full name IE the chat text isn't shown. This roll should be hidden from the players.

Thanks for the great module and I look forward to continue use of it.

Bob

**Comment by eclarke12** [comment]
@bsleys thanks for your interest in CUB. I'll have to verify the initiative one, but for the NPC hp rolls it should respect the sheet roll visibility drop down. Are you saying that's not the case?

**Comment by bsleys** [comment]
Actually on further checking I believe it does respect the drop down. 

So perhaps has a feature request, have an option for it to always hide those rolls IF the Hide NPC names is checked.  It's easy to miss/forget to change that drop down mid game if you have to drop some npc's onto the map and it basically negates the hide names option if as soon as you drop an NPC on the map the players see the NPC name and HP.

Thanks
Bob

**Comment by eclarke12** [comment]
Closing this as I believe 1.2.3 resolved this.
