### ISSUE TITLE
Minor QOL and Concentrator issue with saving throw spells

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#145]
youngfoxToday at 9:43 PM
@tposney @errational [UTC-7] Looks like when both CUB and MQoL are enabled Concentration activates with spells when there is no saving throw, but not when saving throws are requested.

**Comment by tposney** [comment]
I am guessing that CUB looks at the chat card for the spell to decide if the spell requires concentration. When a spell is cast that requires a saving throw the normal chat card is not displayed by minor-qol - just the saving throw roll so there is nothing for cub to find. I'll see if I can include the data that CUB is looking for in the save chat card that minor-qol generates

**Comment by tposney** [comment]
I had a quick look and I can add the div that cub is looking for - data-item-id easily. So I will push that out in the next minor-qol release and there should be no change required to CUB. I've tested in on one case and it seems to work - therefore it will work with all possible cases :)

**Comment by eclarke12** [comment]
Awesome! Yeah I try to use the native functionality from the system (eg.
data-item-id) so that I can stay aligned with core.

**Comment by eclarke12** [comment]
fixed in minor QOL
