### ISSUE TITLE
Notify on double concentration setting doesn't work

### ISSUE THREAD

**Issue by DarKDinDoN** [death-save/combat-utility-belt#148]
Hi, notify on double concentration doesn't work when you change the value in the settings.

Hotfix for me is:

Replacing line 2098 with;

```javascript
choices: {
    "None": "None",
    "GM Only": "GM Only",
    "Everyone": "Everyone"
},
```

Otherwise, the values are set to "0", "1" or "2" and not "None", "GM Only" or "Everyone"

**Comment by eclarke12** [comment]
@DarKDinDoN I think you are still on CUB 0.9.8.2? You may need to uninstall and reinstall to get the latest version. If you have confirmed you are on v1.0.3 let me know and I'll reopen this.

**Comment by DarKDinDoN** [comment]
@eclarke12 You are right. It is now updated.
Still not working tho. Parameter names are different from checks in the code.  

Example in concentrator.js line 424:
`const isWhisper = Sidekick.getSetting(SETTING_KEYS.concentrator.notifyDouble) === "GM Only"`  

Code is waiting for "GM Only" value only when settings set the value to "gm".  
Same for other concentration params.
