### ISSUE TITLE
Attributes such as (dnd5e) inspiration don't show up in Triggler

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#149]
probably not exposed in the Actor.model

**Comment by eclarke12** [comment]
We should add a dropdown of actor types to Triggler to allow the ingestion of the different properties contained on each type.

**Comment by jeremyregnerus** [comment]
I'm not sure if this is dead or not. I've messaged you back in April regarding this, and I wasn't sure if it was every going to amount to anything. Anyway, the property for Inspiration is data.attributes.inspiration wwith a value of 0 or 1. The property for Exhaustion (which also isn't included with triggler) is data.attributes.exhaustion with a value of 0 - 5.

**Comment by eclarke12** [comment]
> I'm not sure if this is dead or not. I've messaged you back in April regarding this, and I wasn't sure if it was every going to amount to anything. Anyway, the property for Inspiration is data.attributes.inspiration wwith a value of 0 or 1. The property for Exhaustion (which also isn't included with triggler) is data.attributes.exhaustion with a value of 0 - 5.

The problem is that these are likely derived attributes which aren't in the template (Which is where Triggler gets its info). I haven't forgotten about this item!

**Comment by jeremyregnerus** [comment]
![image](https://user-images.githubusercontent.com/7407481/102728027-7ad3fa80-42f7-11eb-8944-e8b2f41b8adc.png)
They are included in the template, that's where I retrieved their path.

**Comment by jeremyregnerus** [comment]
It looks like the attributes which are loaded come from the common template only, and do not consider NPC or Character specific properties.

**Comment by eclarke12** [comment]
It doesn't appear to be exposed in `game.system.templates.Actor.templates` which is where Triggler looks:
https://github.com/death-save/combat-utility-belt/blob/d17da8d4289ff8cf44ced79ace2b50e06f687d74/modules/triggler/triggler-form.js#L51

From the screenshot it looks like it's defined in the `character` actor type.

As I said this needs to be improved but it's not top of the list at the moment.

**Comment by eclarke12** [comment]
I'm aware that modules such as DAE do a better job of this, so I will be
looking at their implementation when I work on this.
