### ISSUE TITLE
Don't show players the rolled hp

### ISSUE THREAD

**Issue by shawndibble** [death-save/combat-utility-belt#153]
When rolling a token's hp on drop, only whisper the GM. Don't show the players this information.

https://github.com/death-save/combat-utility-belt/pull/140 should fix this issue.

**Comment by shawndibble** [comment]
update, I hear that 056 has changed how to do gmrolls, so you may need to play around with the PR to make it work for the newer roll settings.

**Comment by shawndibble** [comment]
Confirmed to work in 0.5.7

**Comment by eclarke12** [comment]
NTS: put this behind a setting then use a ternary to set the rollmode

**Comment by Norc** [comment]
This would be awesome to truly hide (including not getting picked up in DSN would be even better).

I always roll everything out in the open (I know, i'm a madlad), but I'd definitely like the HP rolls of the individual mosters to be hidden to add some more chaos err, randomness, to combat.
