### ISSUE TITLE
Linked conditions in chat does not option condition description.

### ISSUE THREAD

**Issue by shawndibble** [death-save/combat-utility-belt#154]
When adding a condition to a token, the chat adds a linked condition, but clicking the link does nothing. This is because the id on the linked condition does not match any entries in the world. Even after importing the condition.

```
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at HTMLAnchorElement._onClickEntityLink (foundry.js:13360)
    at HTMLBodyElement.dispatch (jquery.min.js:2)
    at HTMLBodyElement.v.handle (jquery.min.js:2)
```

Foundry: 0.5.5
CUB: 1.0.3
Browser: Chrome (not tested in other browsers)

Video of issue: https://streamable.com/8mf8y3

**Comment by eclarke12** [comment]
@shawndibble I think this was a bug in foundry 055. Can you please provide more info about the Condition (eg. name, reference source, reference name etc)

**Comment by shawndibble** [comment]
This would be every condition that is from CUB. As can be seen from the video I posted. I can import all the conditions, but the link generated when I apply a condition to the token will not work. Same with conditions I don't import. If this is an issue with 055, then I can wait until the next beta version drops to see if the issue is fixed.

**Comment by eclarke12** [comment]
It shouldn't be necessary to import the Journal entries anymore in case
that's not obvious in the UI, as you can now choose Journal (C) as the
reference source and choose from Compendia

**Comment by shawndibble** [comment]
Confirmed with 0.5.7 that this issue is no longer an problem. Closing.
