### ISSUE TITLE
Removing a condition via chat while the Token HUD is active causes the condition to remain active in the HUD

### ISSUE THREAD

**Issue by sdenec** [death-save/combat-utility-belt#158]
When setting a condition with the token hud menu and removing it via the chat message the token condition menu button does not get deselected (.active class is not removed) and triggers a new condition when deselecting it manually.

Also some conditions - most noticably "unconscious" - can't be removed with the chat message with an error "Condition is not active on token."

**To Reproduce**
1. Open token dondition menu 
2. select condition
3. remove condition via chat
4. open token condition menu again - the removed condition's button is still active

**Expected behavior**
When canceling a condition the token menu should reflect that.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.5.7
 - CUB Version 1.0.3
 - Browser Chrome and Firefox
- OS Windows 10

**Comment by eclarke12** [comment]
validated. great first issue

**Comment by eclarke12** [comment]
> Also some conditions - most noticably "unconscious" - can't be removed with the chat message with an error "Condition is not active on token."
I believe this was resolved in v1.1.1.

The issue remains
