### ISSUE TITLE
Adding status effects to tokens from right-click menu shows chat message even if "Output to Chat" is disabled

### ISSUE THREAD

**Issue by brndd** [death-save/combat-utility-belt#164]
![1590175024574](https://user-images.githubusercontent.com/5822375/82702100-07dba600-9c7a-11ea-916f-724c7b91e257.png)

![1590175044610](https://user-images.githubusercontent.com/5822375/82702102-08743c80-9c7a-11ea-816e-de0d78fd15de.png)

**Comment by eclarke12** [comment]
@brndd this looks like an older version. can you confirm what version you are on?

**Comment by jeremyregnerus** [comment]
I have the opposite issue, I can't find an option to output to chat, and CUB is no longer sending conditions to chat.

**Comment by brndd** [comment]
It was the most recent version at the time of posting this, but I just retested this in the latest version (1.1.1) and it seems this no longer happens.
