### ISSUE TITLE
Duplicating unlinked token maintains HP from original

### ISSUE THREAD

**Issue by megahead11** [death-save/combat-utility-belt#166]
**Describe the bug**
 If you drag out an unlinked token and edit its HP, then duplicate it, the HP of the duplicate will be different than what you changed it to (i.e. the original value before you edited it). This only happens with CUB active. 

**To Reproduce**
1. Create a new actor. Make sure "roll hostile HP" is disabled in settings.
2. Set a token with HP linked to it. Unlink the token from the actor and place it.
3. Change the HP of the set token to a different amount and duplicate it with CTRL + C -> CTRL + V
4. The HP of the second token will be the same HP as original token before modification from step 3.

**Expected behavior**
Without CUB, copying an unlinked token will duplicate current and max HP as expected.

**Screenshots**
https://gyazo.com/697d7d05624ca3f623c1cb7782b5cea2.png
https://gyazo.com/635b912558b984d8249f216726114b69.png
https://gyazo.com/eb2f469e44854b965ed28d44ba747612.png
https://gyazo.com/ba95fb0b2d54f2cb2199fbdf24ab357a.png

**Environment Info (please complete the following information):**
 - Foundry Version: 0.6.0
 - CUB Version 1.0.3
 - Browser : Firefox 76.0.1
- OS Windows 10 (server is hosted on ubuntu)

**Additional context**
Tested only in 5e and with only token tooltips as the other plugin (still happens without it).

**Comment by eclarke12** [comment]
this issue appears to have been resolved at some point
