### ISSUE TITLE
Possible compatablity bug with MQoL

### ISSUE THREAD

**Issue by bsleys** [death-save/combat-utility-belt#188]
With CUB and concentrator working if I enable MQoL concentrator stops working.

Foundry: 0.6.0
DnD 5th Edition: 0.92
CUB: 1.1.1
MQoL: 0.1.19

**Comment by eclarke12** [comment]
hey @bsleys! I can't repro this in
Foundry 064
5e 093
CUB 112
MQOL 0.1.32

can you confirm whether it's still an issue, and if so, please provide some additional info!

**Comment by bsleys** [comment]
Yes it appears to work fine now.

Bob
