### ISSUE TITLE
Any way to turn off the warning messages on each session?

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#192]
They are a bit annoying and not needed for power users so maybe some way to turn them off in settings or have don't show anymore via different dialog, not toast?

![image](https://user-images.githubusercontent.com/4083812/84246401-42b15b00-ab0f-11ea-9da0-ef478fb96865.png)

**Comment by eclarke12** [comment]
This is a PF2e warning not CUB
