### ISSUE TITLE
Add on Triggler the "%" operator listener

### ISSUE THREAD

**Issue by p4535992** [death-save/combat-utility-belt#205]
**Is your feature request related to a problem? Please describe.**
My request feature is not bug related, i just want to track when a "boss" is at 40% of the health and when is at the 20% , i think it's gonna be very useful during the fight.

**Describe the solution you'd like**
A simple solution is add a "%" operator and add a "value2" column for let the user make the operation like this:

category = attributes
attribute = hp 
property1 = value
operator = "%"
value (max hp) = 30
property2 = min
value2 (% value) = 20

so the formula is  X = (20/100 ) * 30 = 6  and answer the question "is current hp < 6 ?"
so when the npc reach "< 6 hp" the triggler start.

**Describe alternatives you've considered**
A alternative and more better solution, but is more work for you, we just set the 

category = attributes
attribute = hp 
property1 = value
operator = "%"
value (% value) = 20

and you recover with the code the max hp  and the current hp of the token and make the same operation

**Additional context**

**Comment by eclarke12** [comment]
Hello @p4535992 , just to confirm there is support for %'s already:
category = attributes
attribute = hp
property1 = value
operator = "="
value = 40%
property2 = max

let me know if I've misunderstood your request!

**Comment by p4535992** [comment]
Wow, very sorry i didn't know i can do that . I must have missed some docuemntation.
Ty very much.

**Comment by eclarke12** [comment]
@p4535992 documentation is missing. It's on my backlog, sorry for the hassle!
