### ISSUE TITLE
Ability to select which conditions get output to chat

### ISSUE THREAD

**Issue by evilcj925** [death-save/combat-utility-belt#220]
**Is your feature request related to a problem? Please describe.**
![Capture](https://user-images.githubusercontent.com/67852506/87843653-21a8fc00-c86b-11ea-8c51-aba81d557429.PNG)
This is the output to chat with a custom condition. Currently the only option regarding output to chat is global, so it is all or nothing, and i like having the default ones output. 
**Describe the solution you'd like**

I would like to be able to choose what conditions are output individually, instead of globally.  
**Describe alternatives you've considered**
An option in the lab to toggle if it output to chat or not. 
**Additional context**

**Comment by eclarke12** [comment]
delivered in v1.3
