### ISSUE TITLE
Enhanced Conditions doing nothing

### ISSUE THREAD

**Issue by dockelso** [death-save/combat-utility-belt#222]
Using newest version of Foundry VTT. 

Enhanced Conditions does not link players to a journal page for the condition once selected from the Assign Status Effects menu. There is also no option to get rid of the stock status effect symbols when Module Settings are opened.

**Comment by eclarke12** [comment]
@dockelso you didn't fill out the bug form so I'm not sure what game system this is related to. Please reply back and let me know.

**Comment by dockelso** [comment]
> 
> 
> @dockelso you didn't fill out the bug form so I'm not sure what game system this is related to. Please reply back and let me know.

Apologies. It's DND5E.

**Comment by eclarke12** [comment]
Can you please update to v1.2 and let me know if you still experience this issue?

**Comment by eclarke12** [comment]
closing issue due to lack of response.
