### ISSUE TITLE
Temporary combatant: "You must define a valid actor type"

### ISSUE THREAD

**Issue by Arkandos** [death-save/combat-utility-belt#228]
**Describe the bug**
When trying to create a temporary combatant in Simple Worldbuilding or Sandbox systems, the following error message is displayed "You must define a valid actor type"

**Steps to reproduce**
1. Press add temporary combatant
2. Add any name in name field
3. Error message
4. No actor or combatant is created

**Screenshots**
![image](https://user-images.githubusercontent.com/5114247/89111919-fe31a400-d45b-11ea-991b-60f85f15f46a.png)

**Environment Info (please complete the following information):**
 - Foundry Version [0.6.5]
 - CUB Version [1.1.3]
 - Foundry software
- OS [Windows 10]
- Simple World-Building [0.36]

**Comment by eclarke12** [comment]
Marked non repro, but looking at it I can pretty much tell right away why it's happening. Adding to 1.2.1
