### ISSUE TITLE
Players can't use CUB

### ISSUE THREAD

**Issue by DangrBoy** [death-save/combat-utility-belt#243]
**Describe the bug**
Sorry if already answered, but I'm having am issue where only a Gamemaster can use Combat Utility Belt, the players can't use it. Am I missing a setting or is that expected functionality?

**Environment Info (please complete the following information):**
 - Foundry Version: both 0.6.6 and 0.7.1
 - CUB Version 1.2]
 - Browser Chrome, Firefox & Opera
- OS Win10

**Additional context**
Tried it with CUB as the only module installed, then tried uninstalling and re-installing CUB, no improvement

**Comment by eclarke12** [comment]
What can't they do @DangrBoy ?

**Comment by DangrBoy** [comment]
It doesn't appear for them at all.

As soon as I switch to a GM account it appears for the GM, but switching back to a player account, there's no CUB buttons on the screen.

**Comment by eclarke12** [comment]
Players are not able to configure CUB, but the functionality will work for
them if it applies...

**Comment by DangrBoy** [comment]
Yeah, but it doesn't, there's absolutely nothing there. No buttons of any kind.

**Comment by eclarke12** [comment]
Let's reset this conversation. What's the functionality you're looking for?

**Comment by DangrBoy** [comment]
Cool. Thanks for sticking with me man, I really appreciate it.

I'm looking for my players to be able to use CUB. As in being able to hover over the 'Equipment' and 'Feats' buttons etc. and have the drop-down menu appear with their 'Weapons' and 'Action' etc.  But right now, with it installed and active, they can't. Nothing appears on their screens when they click on their tokens.

Interestingly, any GM can use CUB for any player as long as the GM connects through a browser. If the GM is using the native Foundry app they also can't see the CUB buttons on the screen.

So, right now, I have one GM logged into the native app, and one logged in via a browser.  The Gm using the browser can see and use CUB whenever they click on an actor's token, the GM using the native app can't!

I'm very confused!

**Comment by eclarke12** [comment]
Can you please open the console (f12) in the browser that isn't working,
and then pasting in a screenshot of any errors (red text) in the console at
the bottom?

**Comment by DangrBoy** [comment]
![image](https://user-images.githubusercontent.com/69125101/92198618-ae167a80-ee29-11ea-87f4-ca8781cbced9.png)

**Comment by eclarke12** [comment]
That's unrelated to CUB and looks like it's coming from your browser. I
definitely suggest using Chrome (or Edge) over Firefox for Foundry.

Can you send a screenshot of the "CUB buttons" also?

**Comment by DangrBoy** [comment]
I tried both of them, neither of them is throwing any errors

**Comment by eclarke12** [comment]
Can you send a screenshot of the buttons that are visible for the GM but
not the user?

**Comment by DangrBoy** [comment]
![image](https://user-images.githubusercontent.com/69125101/92201240-e40b2d00-ee30-11ea-8a40-068e02578666.png)
Chrome, logged in as a GM, CUB button in upper left

![image](https://user-images.githubusercontent.com/69125101/92201157-a908f980-ee30-11ea-8cfe-5145a0c2d44e.png)
Firefox, logged in as player, no CUB buttons in upper left

![image](https://user-images.githubusercontent.com/69125101/92201192-c0e07d80-ee30-11ea-83b7-c79fd16db8f6.png)
Native app, logged in as GM, no CUB buttons in upper left

**Comment by eclarke12** [comment]
Those buttons have nothing to do with CUB. I think they might be related to the Token Hotbar module or something to that effect. For now suggest you investigate that with the author of that module.

**Comment by DangrBoy** [comment]
Yeah, I was starting to wonder that, entirely my bad. Thanks.

**Comment by eclarke12** [comment]
There's a lot of modules. Easy to get them mixed up. If there actually is a bad interaction with CUB and the hotbar module, do reopen.
