### ISSUE TITLE
Handlebars subexpression concatenation error.

### ISSUE THREAD

**Issue by trioderegion** [death-save/combat-utility-belt#246]
**Describe the bug**
Due to an apparent issue with the version of Handlebars, subexpression concatenations do not appear to be working when CUB is enabled with the ICRPG system.

**To Reproduce**
1. Install ICRPG system
2. Create world using ICRPG
3. Enable CUB
4. Create and open character sheet and see missing ability labels (shown below)

**Expected behavior**
The stat labels should appear, but they do not. I believe this is a handlebars version issue and further information is in Additional Context (debugging with ICRPG system dev).

**Screenshots**
![image](https://user-images.githubusercontent.com/14878515/92249414-0b491500-ee98-11ea-9467-62b22bc041cf.png)

**Environment Info (please complete the following information):**
 - Foundry Version: [0.6.6]
 - CUB Version [1.2.1]
 - Browser [chrome, edge, standalone client]
- OS [Windows 10]

**Additional context**
I have debugged the issue with the ICRPG system creator. It appears that its a version of Handlebars in use by CUB that is preventing subexpression concatenation. https://github.com/TomCosaert/FoundryVTT-ICRPG/issues/2

**Comment by eclarke12** [comment]
This is caused by both the module and system implementing a `concat`
Handlebars helper. I have commented on the issue in the ICRPG repo.

**Comment by eclarke12** [comment]
https://gitlab.com/foundrynet/foundryvtt/-/issues/3533
