### ISSUE TITLE
Allow for conditions to link to macros

### ISSUE THREAD

**Issue by NateHawk85** [death-save/combat-utility-belt#254]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but it would be nice to be able to run macros upon applying a condition. This would allow CUB to integrate well with Token Magic FX.

**Describe the solution you'd like**
Perhaps another "row" below Journal to link to a specific macro.

**Comment by eclarke12** [comment]
duplicate of #110 
please upvote that issue or provide comments there
