### ISSUE TITLE
Doom/Churn/Darkness points and Momentum pool/tracker

### ISSUE THREAD

**Issue by GMLovlie** [death-save/combat-utility-belt#261]
A tool to track/add points to pools. I have two kind of pools/trackers in mind:

1. The **points in this pool is can used/spent by the GM** to activate threats, increase threats, and otherwise make life interesting for the players. Because the tracker/pool depends on the success or actions of the players, in some games **the players should also be able to add to this pool** themselves in order to add dice to their hand or otherwise improve their chances of survival/success (adding Doom/Heat/Threat in Conan, Infinity, Star Trek, John Carter from Mars) or to re-roll dice pools (Pray to the Icons in Coriolis), and I'm sure other games with similar mechanics. In The Expanse, players do not add Churn points themselves, even if the number of points added to the tracker is dependent on their success and degree of success. The Churn tracker also goes through three stages of potential activation (at 10 and 20 points) where minor and major effects have a chance of occurring, and at 30 points, where something bad definitely occurs.

2. A second pool available to the group of players, that **the players add points to and spend points from**. This is particularly useful in games like Conan, Infinity, Star Trek, where it is called a Momentum Pool. **It should be possible to cap it at a number, the default being six.** If possible, this pool should also be possible to be made personal, one for each player for games such as John Carter, where players have a personal momentum pools, and where the cap is linked to a character's attribute.

**Comment by eclarke12** [comment]
For scope reasons I'm going to restrict this to a single shared pool for now.

Here's my idea for an initial solution for this:
- Setting to store the following:
- - Pool type (eg. dice, icons, points etc)
- - Current pool value
- - Min pool value (optional)
- - Max pool value (optional)
- Setting for pool name
- Setting for whether players can adjust this value
- Setting for whether players should see this value

Front End:
- An `application` instance that sits on the screen displays the name, value, min/max (if set), and has buttons to add/remove points

**Comment by GMLovlie** [comment]
Sounds great. I see that whoever made the Coriolis system has built something like this in already, so it may be worth a look.

For personal pools players could easily use a note section on their character sheet.

**Comment by eclarke12** [comment]
@GMLovlie sorry to say I've changed my mind on this. I'm not looking to add any new gadgets (features) to CUB. I believe if there's not an existing module already for this, one could be requested here: https://trello.com/b/xYiqr7js/league-of-extraordinary-foundryvtt-developers
