### ISSUE TITLE
Foundry v0.7.5 testing

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#278]
environment: CUB v1.3.1

### Dialog spawned on combat end
- [x] Pass
(Pass/Fail notes)

### XP distributed correctly
- [x] Pass
(Pass/Fail notes)

### Auto-set Concentrating condition on spell cast
- [x] Pass
(Pass/Fail notes)

### Output to Chat
- [x] Pass
(Pass/Fail notes)

### Prompt for check on damage
- [x] Pass
(Pass/Fail notes)

### Notify double-concentration
- [x] Pass
(Pass/Fail notes)

### Condition Lab loads
- [x] Pass
(Pass/Fail notes)

### Game System detected
- [x] Pass
(Pass/Fail notes)

## Macro methods work
- [x] Pass
(Pass/Fail notes)

### Outputs to Chat
- [x] Pass
(Pass/Fail notes)

### Remove default conditions works
- [x] Pass
(Pass/Fail notes)

### Hide NPC names in chat
- [x] Pass
(Pass/Fail notes)

### Hide NPC names in combat tracker
- [x] Pass
(Pass/Fail notes)

### Hide NPC names in combat tracker tooltip
- [x] Pass
(Pass/Fail notes)

### Reroll on Round Change
- [x] Pass
(Pass/Fail notes)

### Detects actor properties
- [x] Pass
(Pass/Fail notes)

### Triggers fire on update
- [x] Pass
(Pass/Fail notes)

### Pans on turn
- [x] Pass
(Pass/Fail notes)

### Pan respects GM/player setting
- [x] Pass
(Pass/Fail notes)

### Selects on turn
- [x] Pass
(Pass/Fail notes)

### Select respects GM/player setting
- [x] Pass
(Pass/Fail notes)

### Correctly sets HP when enabled
- [x] Pass
(Pass/Fail notes)

### Initiative from sheet works
- [x] Pass
(Pass/Fail notes)

### Edit tracked resource works
- [x] Pass
(Pass/Fail notes)

### Auto Roll Hostile HP correctly rolls when hostile token dropped
- [x] Pass
(Pass/Fail notes)

### Resize effects works
- [x] Pass
(Pass/Fail notes)

**Comment by Amuxix** [comment]
I ran a session with 0.7.4 using CUB 1.2.3
Everything that's missing was not tested.
Here is my contribution to this:
### Award XP
- [x] Dialog spawned on combat end
- [x] XP distributed correctly
### Concentrator
- [x] Auto-set Concentrating condition on spell cast
- [x] Output to Chat
- [x] Prompt for check on damage
Notify double-concentration

### Enhanced Conditions
- [x] Condition Lab loads
- [x] Game System detected
It sets the conditions but removing them via the token hud doesn't work, only clicking on the chat message.

### Macro methods work
- [x] Outputs to Chat
- [x] Remove default conditions works

### Hide NPC Names
- [x] Hide NPC names in chat
- [x] Hide NPC names in combat tracker
- [x] Hide NPC names in combat tracker tooltip

### Triggler
Custom conditions seems to fire when using with conditions lab

### Token - Misc
- [x] Auto Roll Hostile HP correctly rolls when hostile token dropped
