### ISSUE TITLE
Error in Condition Lab Foundry VTT 0.7.4 on new row creation

### ISSUE THREAD

**Issue by carltheape** [death-save/combat-utility-belt#282]
Since updating to the 0.7.4 foundry, when trying to create a new status row I am getting:
`condition-lab.js:195 Uncaught (in promise) TypeError: this._getFormData is not a function`

**Comment by eclarke12** [comment]
Thanks for the issue @carltheape ! CUB is not compatible with Foundry 074, however I am working on a new update that will restore compatibility.

**Comment by carltheape** [comment]
Appreciate it!  Love your mod
