### ISSUE TITLE
Applying all conditions at once

### ISSUE THREAD

**Issue by Thedvdias** [death-save/combat-utility-belt#293]
**Describe the bug**
When trying to apply a condition all symbols light up and token gets "Blinded" condition.

**To Reproduce**
1. Place token on Scene
2. Apply any condition to it

**Screenshots**
Trying to apply poison:
![image](https://user-images.githubusercontent.com/41130489/97082112-2b2ac880-15ff-11eb-94f4-193db2fb5a52.png)

Result:
![image](https://user-images.githubusercontent.com/41130489/97082126-3ed62f00-15ff-11eb-8e1f-377bbe53f7ae.png)

When Dynamic Active Effects is enabled this shows:
![image](https://user-images.githubusercontent.com/41130489/97082133-57464980-15ff-11eb-8d4a-b8369bbdbf69.png)

**Environment Info:**
 - Foundry Version: 0.7.5
 - CUB Version : 1.3.0
 - OS Windows 10

**Additional context**
Recently migrated form 0.6.6 to 0.7.5.
Thought it may be something with dynamic effects but after disabling it nothing changed

**Comment by eclarke12** [comment]
can you please test with v1.3.1 and let me know thank you!

**Comment by Thedvdias** [comment]
Yes it is fixed now
