### ISSUE TITLE
Overlay conditions no longer apply image as overlay

### ISSUE THREAD

**Issue by Aeristoka** [death-save/combat-utility-belt#295]
**Describe the bug**
Overlay conditions no longer apply overlay

**To Reproduce**

1. Create condition that applies overlay (ie, hp = 0 for NPCs, apply skull.svg as an overlay)

**Expected behavior**
Apply the selected condition as an overlay, not as a normal condition

**Screenshots**
![image](https://user-images.githubusercontent.com/7988297/97085222-62867e80-15d9-11eb-8b2b-a861c2303343.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.5
 - CUB Version 1.3.0
 - Browser Chrome
- OS Windows 10

**Comment by apoapostolov** [comment]
Hello, I also found this issue might be a conflict with Illandril's Token HUD Scale mod. 
Issue here : https://github.com/illandril/FoundryVTT-token-hud-scale/issues/6

**Comment by apoapostolov** [comment]
Illandril fixed the issue in Toekn HUD Scale.

**Comment by eclarke12** [comment]
woohoo Doing nothing pays off again...
