### ISSUE TITLE
Use @Sky's Icon Setter to easily set conditions on multiple tokens

### ISSUE THREAD

**Issue by cgplayer2000** [death-save/combat-utility-belt#296]
@Sky's[ Icon Setter]( https://raw.githubusercontent.com/Sky-Captain-13/foundry/master/icon-setter/icon-setter/module.json) allows one to target multiple tokens and use a macro to set an icon.  As an enhancement, it'd be  useful to allow one to use this to set conditions through the Condition Lab on multiple tokens at the same time.

**Comment by eclarke12** [comment]
CUB already has macro methods to apply conditions to one or more tokens or actors. Please check out the API docs (https://github.com/death-save/combat-utility-belt/blob/master/api.md) for more info.

There will be improvements to these methods in v1.3.1 so I will be closing this issue with that release.
