### ISSUE TITLE
Set condition error

### ISSUE THREAD

**Issue by Cododoc** [death-save/combat-utility-belt#306]
**Describe the bug**
When I try to set any condition, there "Blinded" condition sets.

**To Reproduce**
1. Select token.
2. Assign status effect
3. Select ant condition.

**Expected behavior**
Properly condition sets.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.5
 - CUB Version 1.3.1
 - Browser Chrome
- OS Windows 10

**Additional context**

**Comment by Cododoc** [comment]
I found Condition Lab menu. I pressed Reset Mapping and problem gone.
Possible it some kind update issue. I did not setup anything there before.

**Comment by eclarke12** [comment]
thanks for this. I pushed out a hotfix right after I pushed out 1.3.1.

**Comment by eclarke12** [comment]
closing this issue. if others experience it a new issue can be opened
