### ISSUE TITLE
Missing proper path to variable?

### ISSUE THREAD

**Issue by szefo09** [death-save/combat-utility-belt#307]
https://github.com/death-save/combat-utility-belt/blob/d2b3729c262298e5a7dd049fcf4c659a4cfae3b3/modules/enhanced-conditions/enhanced-conditions.js#L119
https://github.com/death-save/combat-utility-belt/blob/d2b3729c262298e5a7dd049fcf4c659a4cfae3b3/modules/enhanced-conditions/enhanced-conditions.js#L120

Should it be `effect: cubOption.updateOverlay` instead of `effect: updateOverlay`, and `cubOption.existingOverlay` instead of `existingOverlay`?

**Comment by eclarke12** [comment]
yep good catch.
