### ISSUE TITLE
Editing Active Effect for a Condition before saving the mapping causes the wrong Effect to be edited

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#312]
Currently if you Add a Row to the Condition Lab, then click the Configure Active Effects button, it will open the config for the first(?) Condition due to the fact that the newly added row does not have a Active Effects data property.

WORKAROUND: Save the Lab mapping before editing the Active Effect

**Comment by Norc** [comment]
Even after saving and reopening, it opens the window but I get this:
![image](https://user-images.githubusercontent.com/64667579/97202070-88528580-1789-11eb-897b-840d59f504d3.png)
