### ISSUE TITLE
Setting any CUB condition results in the 'Charmed' condition

### ISSUE THREAD

**Issue by cgplayer2000** [death-save/combat-utility-belt#314]
Setting any CUB-related condition through the right-click HUD results in setting the Charmed condition.

To Reproduce:
1.  Have a character token active in your scene.
2.  Right-click on it and then click on the Assign Status Effect.
3.  Click on any CUB condition icon.
4.  It sets the token to the Charmed condition.

https://gyazo.com/474636e7b4c53ef8c9db2af762ed7bac

Expected Behavior:  Clicking on a condition icon sets the corresponding icon on the token.

There are no error messages in console, but there is a warning:
![image](https://user-images.githubusercontent.com/10798879/97248602-8663e300-17d8-11eb-85cc-183fc01db588.png)

**Environment Info (please complete the following information):**
 - Foundry Version: [0.7.5]
 - CUB Version [1.3.1]
 - Browser [Chrome 86i]
- OS [Windows 10]

**Comment by eclarke12** [comment]
@cgplayer2000 the gsap warnings could be a number of modules (including CUB) that rely on a library that was accidentally removed in 075
regarding your issue, can you try going into the Condition Lab and clicking save, then try setting a Condition

**Comment by cgplayer2000** [comment]
Hmmm, when I first opened Condition Lab, I didn't have any of the buttons at the bottom of the window.  I opened one of the Active Effect dialog boxes (for Hex, I think), and then the buttons reappeared.  I clicked the save mapping button, and then I was able to activate conditions as expected.  Not sure why, but that fixed things.
