### ISSUE TITLE
'Hide Names' Not working with Savage Worlds

### ISSUE THREAD

**Issue by Freewolf2000** [death-save/combat-utility-belt#317]
**Describe the bug**
I am running this module mainly for status effects. I am using the Savage Worlds game system, which I know this was not mainly built with. However when ticking the 'Enable Hide Actor Names' it is not hiding the actor names in the Chat Log. This happens every time a skill roll is made that displays to the Chat Log.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.5
 - CUB Version 1.2.3
 - Browser Firefox
- OS Windows 10

**Comment by eclarke12** [comment]
Hi @Freewolf2000 please ensure you update to CUB v1.3.7 (coming out later today) and try again, as it seems to be working for me. Older versions of CUB are not supported, sorry.

Additionally/alternately, go into the CUBputer and ensure you have Hide Names enabled for the dispositions you want to hide:
![image](https://user-images.githubusercontent.com/42503461/100942840-ebce8200-34b0-11eb-9b94-0bc5dbe937e9.png)
