### ISSUE TITLE
Concentration Icon Endless Stacking and Unclearable

### ISSUE THREAD

**Issue by VoltCruelerz** [death-save/combat-utility-belt#318]
**Describe the bug**
Repeatedly casting a concentration spells will not clear old concentration states and result in an endless and unclearable stack of concentration statuses.

![image](https://user-images.githubusercontent.com/4068550/97352807-7fd17c00-1869-11eb-9600-081e9d7d6799.png)

**To Reproduce**
1. Run with Concentrator turned on.
2. Cast a concentration spell.
3. Cast another concentration spell.
4. See that original icon is not cleared.
5. Attempt to manually set/unset the Concentration status through the token status menu, observing that this creates/deletes yet another one, but those programmatically created are unclearable.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.5
 - CUB Version: 1.3.1
 - Browser:  Chrome
- OS: Windows 10

**Comment by MSAbaddon** [comment]
As an addition - if players cast a concentration spell Concentrator sends the message that a concentration spell is already active even though the according token does not have the concentrating condition. This even occurs if I deactivate Concentrator in the CUB options.

**Comment by eclarke12** [comment]
@VoltCruelerz can you please confirm this is still happening in v1.3.2? I'm having trouble reproducing this as a GM or player

**Comment by VoltCruelerz** [comment]
Thanks, that worked!
