### ISSUE TITLE
Active Effect configuration does not work for some conditions

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#326]
Stunned works:
https://cdn.discordapp.com/attachments/751602144414531706/771020672575078430/unknown.png

Unconscious does not work:
https://cdn.discordapp.com/attachments/751602144414531706/771020751763275796/unknown.png

**Comment by JLtheking2** [comment]
To add on to this, on my end, I can't seem to get the active effects settings (e.g. duration) that i have set up in the Condition Lab to transfer properly onto tokens when they are given that condition.

With regards to some conditions not working, I get the same "Undefined" text as eclarke12's second picture for my custom conditions, but it looks fine on the default included conditions (still have the problem mentioned above though).

**Comment by Linith** [comment]
I too get this when creating newer conditions post 7.5..
All my pre 7.5 conditions are correct and filled out.
