### ISSUE TITLE
Feature Request - Add a new tool "Active Effects Lab"

### ISSUE THREAD

**Issue by p4535992** [death-save/combat-utility-belt#334]
**Is your feature request related to a problem? Please describe.**

It is not related to a problem, but more an enchantment of the module.

With the advent of "Active Effects" many things are changing and reading the article on the application of Active Effects ([methods_for_passive_bonuses_to_attacks_using_dae](https://www.reddit.com/r/FoundryVTT/comments/jk8mlr/methods_for_passive_bonuses_to_attacks_using_dae/), example E) , I realized that it would make the use of AE very dynamic with the support of the Condition Lab.

The idea is to create a new component "very similar" to the Condition Lab that could be called "Active Effects Lab", with the additional integration of the macro from the same article, so you could create your own active effects separated from the conditions in a more dynamic way and can be activated directly on the token as the activations of the conditions are currently.

This is the idea, but there may be some better vision than mine.

**Describe the solution you'd like**

A new component "very similar" to the Condition Lab that could be called "Active Effects Lab", with the additional integration of the macro from the same article, so you could create your own active effects separated from the conditions in a way dynamic and can be activated directly on the token as the activations of the conditions are currently.

**Describe alternatives you've considered**

**Additional context**

**Comment by eclarke12** [comment]
Thanks for this issue. Currently I'm not really looking to increase the scope of CUB to include additional features. For now I am fairly happy with how Active Effects are integrated into Conditions and there are other tools like DAE (for dnd5e) to manage Active Effects.

**Comment by p4535992** [comment]
KK, ty for your time.
