### ISSUE TITLE
Bloodied and Skull markers are not auto applying anymore

### ISSUE THREAD

**Issue by Avitale34** [death-save/combat-utility-belt#336]
**Describe the bug**
The Bloodied and Skull markers are not auto applying anymore

**To Reproduce**
1. I recently deleted the "d&d 5e Conditions" module and now CUB is not applying bloodied or skull markers automatically. Using newest version of foundry and CUB.

**Comment by eclarke12** [comment]
Automatic application of Conditions requires the creation of triggers using Triggler.

Please review this wiki page: https://github.com/death-save/combat-utility-belt/wiki/triggler

Additional assistance can be provided on the Foundry or Death Save discord
