### ISSUE TITLE
Custom On-hit Spell Triggers & AoO triggers

### ISSUE THREAD

**Issue by NoBullPleb** [death-save/combat-utility-belt#342]
I would like for Triggerly to be customizable for when: 
- I am hit with an attack and have a spell that triggers on attack (such as shield or Hellish Rebuke), give me a pop up that asks if I want to use it. 
- Allow me to customize a trigger for asking me if I want to make an AoO when a creature leaves *or* enters my threat range (range customizable)

**Comment by eclarke12** [comment]
These are good ideas, but out of scope for what Triggler is intended to be. I suggest looking into Midi QOL as an option for this kind of automation. https://foundryvtt.com/packages/midi-qol/
