### ISSUE TITLE
Active Effects are tied to the array position of a Condition instead of the Condition itself

### ISSUE THREAD

**Issue by Havoclivekiller** [death-save/combat-utility-belt#351]
**Describe the bug**
Effects are based on the position on the list, not the condition. I've moved a condition in the Condition Lab and it had different active effects.

**To Reproduce**
Rearrange Conditions in Conditions Lab and check their effects

**Expected behavior**
Conditions should have effects always connected, no matter their position on the list

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.7
 - CUB Version 1.3.3
 - chrome
- Windows 10

**Additional context**

**Comment by eclarke12** [comment]
This behaviour is unfortunately expected with the current implementation. I have a fix I'm targeting for next update.
