### ISSUE TITLE
Condition Lab not opening when used alongside specific module

### ISSUE THREAD

**Issue by dstein766** [death-save/combat-utility-belt#355]
**Describe the bug**
When used with Plutonium 1.14.6, Condition Lab won't open.

**To Reproduce**
1. Enable ONLY Plutonium 1.14.6 and CUB 1.3.4
2. Click on Condition Lab.

**Expected behavior**
Condition Lab data entry form should open.  It does not.
Disabling Plutonium = form opens as expected.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.6
 - dnd5E: 1.1.1
 - CUB Version 1.3.4 (worked fine prior to this)
 - Browser Chrome Version 86.0.4240.198 (Official Build) (64-bit) AND Firefox 82.0.3 (64-bit)
-  OS self-hosted on windows 10 (Version 2004 (OS BUild 19041.630))

**Additional context**
Problem began immediately after installation of today's CUB 1.3.4 update.  
FWIW: my Firefox test instance has ZERO browser extensions.  
The console shows NO error messages.  Upon clicking "Condition Lab" the console displays "Foundry VTT | Rendering ConditionLab" but no additional relevant messages., and definitely no error messages.

Am wondering if this is somehow related to this change, as per CHANGELOG??  "Fixed Condition Lab not opening in worlds where the game system was unknown to CUB"

**Comment by eclarke12** [comment]
Sorry I don't support compatibility with tools that are designed to circumvent copyright. Please feel free to raise an issue on the Plutonium issue tracker

**Comment by dstein766** [comment]
I was actually in the process of closing the issue because, post-reboot, 
while the problem persisted it was no longer happening specifically with 
the named module. - i.e. enable just those 2 modules wasn't enough to 
cause the problem again as it had pre-reboot.

Post-reboot and lots of turning things on/off it seems like the culprit 
is some interaction between CUB and MagicItems 2.0.3.  Toggling that 
module on/off creates/fixes the problem.  I don't currently make use of 
MagicItems so I've simply disabled it, so not a big issue for me, but 
fyi.



------ Original Message ------
