### ISSUE TITLE
Bug with fresh install, Signal.js is missing.

### ISSUE THREAD

**Issue by valdier1** [death-save/combat-utility-belt#358]
**Describe the bug**
![2020-11-14 21_12_03-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/13425341/99171489-549ab980-26be-11eb-92db-eef9566d2a54.png)
.png)

**To Reproduce**
Fresh install of CUB

**Expected behavior**
It to work :)

**Screenshots**
Added above

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.7
 - CUB Version 1.3.5
 - Browser: Chromium
- OS: Windows 10

**Additional context**
Exactly as shown above. I've uninstalled, reinstalled, same issue

**Comment by eclarke12** [comment]
It's definitely in the zip. I just created a brand new server and installed the module and not getting the error.

**Comment by valdier1** [comment]
I can show you a video of doing exactly this reproduceable 100% of the time? I will download the zip directly if it helps

**Comment by valdier1** [comment]
Installing manually (download zip) works fine, but... this might be an issue with FVTT itself that several people are seeing in various places recently. Users permissions are not getting access to write/modify files and it's causing issues in at least some cases. In this case, perhaps with the installer not placing files where they are needed?

**Comment by eclarke12** [comment]
I see, I'm sorry to hear that, but it seems like an issue that should be raised on the Foundry issue board? I don't think I can do anything on my end to fix that part.

I'm going to close this for now, but if you feel there is something more I can do, please drop a comment or reopen the issue.
