### ISSUE TITLE
CUBPuter doesn't open

### ISSUE THREAD

**Issue by Havoclivekiller** [death-save/combat-utility-belt#359]
**Describe the bug**
When I click on either CUBPuter buttons, it doesn't open for some unknown reason. There's no error in the console log, only "Foundry VTT | Rendering CUBPuter".

**To Reproduce**
1. Click on CUBPuter button

**Expected behavior**
Window of CUBPuter to open

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.7
 - CUB Version 1.3.5 (but I've had this problem since version 1.3.3 or maybe 1.3.2)
 - Browser Chrome
- OS Windows 10

**Additional context**
I've had this problem since version 1.3.3 or maybe 1.3.2

**Comment by Havoclivekiller** [comment]
Found which module that was doing this "ViNo - VIsual NOvel" module.

**Comment by eclarke12** [comment]
Hmm that's an odd one. I will leave this open so I can investigate when time allows

**Comment by Havoclivekiller** [comment]
Author of ViNo fixed it with his new release. 1.5
