### ISSUE TITLE
Condition Lab - Save Mapping removes all Active Effects

### ISSUE THREAD

**Issue by Havoclivekiller** [death-save/combat-utility-belt#360]
**Describe the bug**
When I click on Save Mapping, it removes all Active Effects from my conditions.

**To Reproduce**
1. Add effects
2. Click on Save Mapping
3. Check effects

**Expected behavior**
Active effects to be saved

**Screenshots**
https://imgur.com/vJpQ2wo (webm)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.7
 - CUB Version 1.3.5
 - Browser Chrome
- OS Windows 10

**Additional context**
Never had this problem in 1.3.3 (or maybe 1.3.2) and before.

**Comment by amcvfx** [comment]
I just had this issue as well. I had set up Active Effects for most of my Conditions and after updating and saving the mapping (as instructed by the popup window) all of the active effects are gone.

**Comment by JLtheking2** [comment]
Yes I am having this issue as well.

**Comment by Flop35190** [comment]
Me too

**Comment by eclarke12** [comment]
typo sorry
update line 289 of condition-lab.js to `const activeEffect = existingCondition ? existingCondition.activeEffect : null;` (will be fixed in CUB v1.3.6)

**Comment by JLtheking2** [comment]
That fix seems to work for the saving part, but it still does not seem to transfer the Active Effect over to the target for me.

I have set up several "Used X resource" conditions and given them a duration of 1 round. 
https://imgur.com/a/jluE8R1

But when i give the condition manually to a token (via right click and selecting the icon), the Active Effect added to the token (via checking the token's Effects tab) does not seem to transfer the 1 round duration over.

I tested this with no modules activated and only CUB.

**Comment by eclarke12** [comment]
> That fix seems to work for the saving part, but it still does not seem to transfer the Active Effect over to the target for me.
> 
> I have set up several "Used X resource" conditions and given them a duration of 1 round.
> https://imgur.com/a/jluE8R1
> 
> But when i give the condition manually to a token (via right click and selecting the icon), the Active Effect added to the token (via checking the token's Effects tab) does not seem to transfer the 1 round duration over.
> 
> I tested this with no modules activated and only CUB.

Was this working prior to 1.3.5? I'm wondering if you might be conflating this issue with a general lack of functionality around Active Effects in CUB--it's not a fully fleshed out system just yet!

**Comment by JLtheking2** [comment]
Oh, then it that case, no - it didn’t used to work.

The bug of custom conditions not being able to have editable Active Effects (fixed in 1.3.5) was always around since the switch to Active Effects in 1.3.0. And at that point I didn’t know exactly what features were intentionally unimplemented or didn’t work because of the aforementioned bug.

Is this a planned feature? I would like to customize the Active Effect that is granted to tokens when they get a condition (e.g. Grappled causing the token to have a speed of 0).

**Comment by Havoclivekiller** [comment]
Strange. I had it working. For example, I've set Half Cover condition, set +2 ac and +2 dex save, gave the condition and saw the stats change.

**Comment by JLtheking2** [comment]
I only tested with the duration field, as shown in my image. It might just be that that isn’t working then.
