### ISSUE TITLE
Active effects configured in the Condition Lab are not saved

### ISSUE THREAD

**Issue by SalieriC** [death-save/combat-utility-belt#368]
**Describe the bug**
When setting up active effects in the Condition Lab on a specific status and save is clicked the active effect is present. But once the save button on the Condition Lab is clicked, all Active Effecrs are reset/deleted.

**To Reproduce**
1. Go to the Condition Lab.
2. Click on "Active Effect Config" on one status.
3. Set up an Active Effect.
4. Click "Submit Changes". The AE is set up and visible if step 2 is repeated.
5. Click "Save Mapping". A Message will appear informing of the save status. Repeat step 2 and you'll notice that AEs are gone.

**Expected behavior**
AEs should be saved instead of resetted.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.6
 - Game System / Version: SWADE 0.14.0
 - CUB Version 1.3.5
 - Browser Foundry application
 - Windows

**Additional context**
This bug appears on worlds which had CUB installed prior to CUB version 1.3.5 as well as on new worlds. This did **not** happen on versions prior to 1.3.5 (if the Condition Lab was accessible due to a prior set up).
I consider a fix on it to be urgent as it is stripping the game and module of a rather essential mechanic and one of the few reasons to use CUB on non-DnD systems.

**Comment by eclarke12** [comment]
Please try updating to CUB v1.3.6 and let me know if the issue is still occurring.

**Comment by SalieriC** [comment]
It doesn't. Sorry for the delay.
