### ISSUE TITLE
Triggler no long applies conditions

### ISSUE THREAD

**Issue by Rawrly85** [death-save/combat-utility-belt#428]
In the recent update, the condition no longer get applied that are setup via Triggler. Specifically the ones I've tried are
>25% add a bleed
< 25% remove bleed
>0 Death
< Unapply death

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.7
 - Game System / Version:  dnd5e 1.1.1
 - CUB Version 1.3.7
 - Chrome
 - Windows 10

**Additional context**

**Comment by eclarke12** [comment]
I can't replicate this issue.

can you provide some screenshots of your triggers? While you're in triggler, try resaving the triggers and see if that has any effect. 

Thanks!

**Comment by Rawrly85** [comment]
Confirmed that once save on each world that I had previous triggered on, that it started to work again.
