### ISSUE TITLE
Importing a Condition Map fails to import active effects

### ISSUE THREAD

**Issue by amcvfx** [death-save/combat-utility-belt#429]
**Describe the bug**
Importing a Condition Map doesn't import the Active Effects set up for the conditions. 
I can see in the .json file that the Configured active effects have been exported but they are not there when the Condition map is brought into another world.

I have tried both importing over an existing map in Condition Lab as well as resetting back to defaults before importing and neither seem to work.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.8
 - D&D 5th 1.1.1
 - CUB Version 1.3.7
 - Chrome
 - Windows 10

**Comment by HippyCraig** [comment]
I having the same issue I can see the exported Active Effects in the JSON file, they just dont import.  If there is some detail I can provide please let me know.  Latest version of FVTT 7.8 and Latest CUB 1.3.8

**Comment by ralke1** [comment]
I have the same issue. It doesn't seem to import any effect. 

Here follows the .json tested with all conditions working 100%. 

`{
  "system": "dnd5e",
  "map": [
    {
      "id": "blinded",
      "name": "Blinded",
      "icon": "modules/combat-utility-belt/icons/blinded.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.Ux6txAl8deaFfVai]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Blinded",
        "icon": "modules/combat-utility-belt/icons/blinded.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.disadvantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.advantage.attack.all",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "charmed",
      "name": "Charmed",
      "icon": "modules/combat-utility-belt/icons/charmed.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.ALX4MqfO4qthkvze]",
      "applyTrigger": "",
      "removeTrigger": "",
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "concentrating",
      "name": "Concentrating",
      "icon": "modules/combat-utility-belt/icons/concentrating.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.cm3YSYDIMDvpDXOr]",
      "applyTrigger": "",
      "removeTrigger": "",
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "deafened",
      "name": "Deafened",
      "icon": "modules/combat-utility-belt/icons/deafened.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.ILvITvmSVY8aNkRD]",
      "applyTrigger": "",
      "removeTrigger": "",
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "exhaustion-1",
      "name": "Exhaustion 1",
      "icon": "modules/combat-utility-belt/icons/exhaustion1.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.SqHi8Xo9Cj5FGcc7]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Exhaustion 1",
        "icon": "modules/combat-utility-belt/icons/exhaustion1.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.disadvantage.ability.check.all",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "exhaustion-2",
      "name": "Exhaustion 2",
      "icon": "modules/combat-utility-belt/icons/exhaustion2.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.SqHi8Xo9Cj5FGcc7]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Exhaustion 2",
        "icon": "modules/combat-utility-belt/icons/exhaustion2.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "data.attributes.movement.walk",
            "mode": 1,
            "value": 0.5
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "exhaustion-3",
      "name": "Exhaustion 3",
      "icon": "modules/combat-utility-belt/icons/exhaustion3.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.SqHi8Xo9Cj5FGcc7]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Exhaustion 3",
        "icon": "modules/combat-utility-belt/icons/exhaustion3.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.disadvantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.disadvantage.ability.save.all",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "exhaustion-4",
      "name": "Exhaustion 4",
      "icon": "modules/combat-utility-belt/icons/exhaustion4.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.SqHi8Xo9Cj5FGcc7]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Exhaustion 4",
        "icon": "modules/combat-utility-belt/icons/exhaustion4.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "data.attributes.hp.max",
            "mode": 1,
            "value": 0.5
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "exhaustion-5",
      "name": "Exhaustion 5",
      "icon": "modules/combat-utility-belt/icons/exhaustion5.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.SqHi8Xo9Cj5FGcc7]",
      "applyTrigger": "",
      "removeTrigger": "",
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "frightened",
      "name": "Frightened",
      "icon": "modules/combat-utility-belt/icons/frightened.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.tGTkfptJtSGJr1Xh]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Frightened",
        "icon": "modules/combat-utility-belt/icons/frightened.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.disadvantage.ability.check.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.disadvantage.attack.all",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "grappled",
      "name": "Grappled",
      "icon": "modules/combat-utility-belt/icons/grappled.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.zesSULZzbAgZqH1e]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Grappled",
        "icon": "modules/combat-utility-belt/icons/grappled.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "data.attributes.movement.walk",
            "mode": 5,
            "value": 0
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "incapacitated",
      "name": "Incapacitated",
      "icon": "modules/combat-utility-belt/icons/incapacitated.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.wSnqNSNXrBKhxxeu]",
      "applyTrigger": "",
      "removeTrigger": "",
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "invisible",
      "name": "Invisible",
      "icon": "modules/combat-utility-belt/icons/invisible.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.OsOee5gTA3hq99UC]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Invisible",
        "icon": "modules/combat-utility-belt/icons/invisible.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.grants.disadvantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.advantage.attack.all",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "paralyzed",
      "name": "Paralyzed",
      "icon": "modules/combat-utility-belt/icons/paralyzed.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.7D1PoPDYVdklR9JX]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Paralyzed",
        "icon": "modules/combat-utility-belt/icons/paralyzed.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.fail.ability.save.dex",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.str",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.advantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.critical.mwak",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.critical.msak",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "petrified",
      "name": "Petrified",
      "icon": "modules/combat-utility-belt/icons/petrified.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.AzG2etIEGlcvtbsl]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Petrified",
        "icon": "modules/combat-utility-belt/icons/petrified.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.DR.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.advantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.dex",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.str",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "poisoned",
      "name": "Poisoned",
      "icon": "modules/combat-utility-belt/icons/poisoned.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.QAzXOTJ1qhxtsxxs]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Poisoned",
        "icon": "modules/combat-utility-belt/icons/poisoned.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.disadvantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.disadvantage.ability.check.all",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "prone",
      "name": "Prone",
      "icon": "modules/combat-utility-belt/icons/prone.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.sVdA6KXpTAbtRFmE]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Prone",
        "icon": "modules/combat-utility-belt/icons/prone.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.grants.disadvantage.attack.rsak",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.disadvantage.attack.rwak",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.advantage.attack.msak",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.advantage.attack.mwak",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "restrained",
      "name": "Restrained",
      "icon": "modules/combat-utility-belt/icons/restrained.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.4Vln6a6S1VnBtw5o]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Restrained",
        "icon": "modules/combat-utility-belt/icons/restrained.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.grants.advantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.disadvantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.disadvantage.ability.save.dex",
            "mode": 5,
            "value": 1
          },
          {
            "key": "data.attributes.movement.walk",
            "mode": 5,
            "value": 0
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "stunned",
      "name": "Stunned",
      "icon": "modules/combat-utility-belt/icons/stunned.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.RqvuZKVP5QYpCkUj]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Stunned",
        "icon": "modules/combat-utility-belt/icons/stunned.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.grants.advantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.dex",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.str",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    },
    {
      "id": "unconscious",
      "name": "Unconscious",
      "icon": "icons/svg/unconscious.svg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.KDdGKMdaVa8SSHU7]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": {
        "label": "Unconscious",
        "icon": "icons/svg/unconscious.svg",
        "tint": "",
        "disabled": false,
        "duration": {
          "seconds": null,
          "startTime": null,
          "rounds": null,
          "turns": null,
          "startRound": null,
          "startTurn": null
        },
        "changes": [
          {
            "key": "flags.midi-qol.grants.advantage.attack.all",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.critical.mwak",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.grants.critical.msak",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.dex",
            "mode": 5,
            "value": 1
          },
          {
            "key": "flags.midi-qol.fail.ability.save.str",
            "mode": 5,
            "value": 1
          }
        ]
      },
      "options": {
        "overlay": true,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": true
      }
    },
    {
      "id": "morrendo",
      "name": "Morrendo",
      "icon": "systems/dnd5e/icons/skills/blood_04.jpg",
      "referenceType": "compendium.journalEntry",
      "compendium": "world.condicoes",
      "referenceId": "@Compendium[world.condicoes.3L2zsxnz2DYaSAf0]",
      "applyTrigger": "",
      "removeTrigger": "",
      "activeEffect": null,
      "options": {
        "overlay": false,
        "removeOthers": false,
        "outputChat": true,
        "markDefeated": false
      }
    }
  ]
}
`

**Comment by brunocalado** [comment]
Same in here

**Comment by thebaron002** [comment]
following with same problem

**Comment by siliconsaint** [comment]
+1

**Comment by brunocalado** [comment]
Hi tried to import and still not working.
[cub-dnd5e-condition-map.zip](https://github.com/death-save/combat-utility-belt/files/6097109/cub-dnd5e-condition-map.zip)

**Comment by eclarke12** [comment]
Hey folks, this is going to be my primary focus for the next CUB update but I don't have an ETA at this time. Thanks for your patience.

**Comment by RufusTiki** [comment]
I'm not sure this is the best fix, but a temporary workaround at least, that seems to work for me:
I added the following line to line 422 of condition-lab.js, at the end of the _processImport function (right before this.render()):  
        Sidekick.setSetting(BUTLER.SETTING_KEYS.enhancedConditions.map, this.map, true);
        this.render();

After import, you sometimes still have to close and reopen the Condition Lab to get the Active Effects buttons to be enabled (like you do when adding a new item... not sure why this is the case). But the imported effects are there.

In my debugging it appeared the import was successful, but doesn't get saved. Clicking the Save Mapping button or closing/reopening seems to eventually call _UpdateObject which calls _processFormData which compares the Form with the last saved map and thus overwrites the import. Or at least that's my understanding. 

Hope that helps a bit with a real fix. And also thanks for the great module!

**Comment by gravagehulk** [comment]
I thought I saw in the update notes that this was fixed, but It still wasn't working until I applied the fix from RufusTiki above. Thank you, sir.
