### ISSUE TITLE
Concentrator sending multiple messages to chat

### ISSUE THREAD

**Issue by amcvfx** [death-save/combat-utility-belt#430]
**Describe the bug**
When a token has concentration added and it is already concentrating, the warning message sent to chat appears 7-8 times. Also this message doesn't seem to be able to be turned off in the CUB settings. Even when the setting is set to None the message still shows up in chat.

**To Reproduce**
With just CUB and MidiQOL active the chat is spammed with the double Concentration messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/35099081/101367029-fa001200-38a5-11eb-9ec8-7775d477aa94.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.8
 - Game System / Version: dnd5e 1.1.1
 - CUB Version 1.3.7
 - Chrome
 - Windows 10

**Comment by eclarke12** [comment]
I've had some other reports of this and an indication of the cause so I'll take a look tonight.
