### ISSUE TITLE
Names are not hidden if player is not logged in when message is created

### ISSUE THREAD

**Issue by JimVerhagen** [death-save/combat-utility-belt#441]
**Describe the bug**
Hide Names does not work in my chat. In the Encounter menu it shows 'Unknown Creature' but if I make an attack or any other roll, the name is shown to the players. Also, all public chat messages show the name to the players. As Gamemaster, the mask icon is shown in the chat for all messages of the token.

**To Reproduce**
1. Create new world and one player (Player or Trusted)
2. Create a blank scene
3. Create hostile token and player token, assign player to own the player token
4. Activate only Combat Utility Belt in Manage Module
5. Activate hide names and to hide Hostile Names in 'CUBPuter'
6. Make a roll with the hostile token as gamemaster
7. Log into the player and look at chat: You will see the token name and not 'Unknown Creature'

**Expected behavior**
I expected the name in chat to be hidden. When I see the message as Gamemaster, the mask icon is shown. Yet the players can all see the name in the chat.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.8
 - Game System / Version: dnd5e 1.2.0
 - CUB Version: 1.3.8
 - Browser: Chrome
 - OS: Windows 10

**Comment by eclarke12** [comment]
Possibly something has changed with rolls in dnd5e 1.2.0

**Comment by JimVerhagen** [comment]
I have an update: This bug occurs when a player is not logged in at the moment of the chat message. If a player is logged in when the chat message or roll occurs the module functions as expected. If the player logs out during the session and then logs in again, the message that first showed 'Unknown Creature' now show the actual name.

**Comment by DariusWolfe** [comment]
Having a similar issue with the PF2E System; Names are hidden when the creature speaks IC or rolls, but not when damage is applied to the creature; there it shows the full name of the creature. Every other part of the Hide Names Gadget seems to work just fine with PF2E.

**Comment by CatbotTsumi** [comment]
I'm facing the same issue and I have to add that a simple page refresh will unhide all the hidden names regardless of if they were there when it was posted.

**Comment by eclarke12** [comment]
I believe this was resolved with #527
