### ISSUE TITLE
Superfluous comma added to condition named "hidden" ?! (minor)

### ISSUE THREAD

**Issue by DipsoNOR** [death-save/combat-utility-belt#448]
**Describe the bug**
Here is an odd one: Both me and my friend @Asherett#1138 manually added a condition to CUB called "hidden". Now if we mouse over the condition in the condition menu of a token , or view it in the latest version of token action hud, it's called "Hidden,"

The added comma is nowhere to be seen in the conditions lab setting.

It only appears on this spesific condition for both of us, we both set up the condition manually and independently.

What is going on.... it's so weird and isolated, and appears to only be visual, since everything still works as expected. 

**To Reproduce**
As far as we can tell: Create a custom condition and name it "hidden"... I'll experimented some more when I'm at my workstation.

Only other thing we have done that is indentical is that the condition references a journal entry we have created with the same name.

**Expected behavior**
Well, if it's really how it seems, I expect the phrase "hidden" to behave like all other phrases, and not have an extra comma at the end.

**Screenshots**
If applicable, add screenshots to help explain your problem. (will add when I'm back at my computer)

**Environment Info (please complete the following information):**
 - Foundry Version: [e.g. 0.5.5]
 - Game System / Version: [e.g. dnd5e 1.0.0]
 - CUB Version [e.g. 1.3.0]
 - OS [e.g. Windows 10]

**Additional context**

**Comment by 736dave** [comment]
I get this too.  It created weird behaviour when combined with Conditional Visibility.  Ref:

  "effects": [
    {
      "_id": "6eojnr5MZriq7gWM",
      "flags": {
        "core": {
          "statusId": "combat-utility-belt.hidden"
        },
        "combat-utility-belt": {
          "conditionId": "hidden",
          "overlay": false
        }
      },
      "changes": [],
      "duration": {},
      "icon": "modules/conditional-visibility/icons/newspaper.svg",
      "label": "Hidden,",
      "disabled": true
    },

**Comment by Vagor96** [comment]
Any news on this?

**Comment by Vagor96** [comment]
Nevermind, it is a core foundry bug. The comma is in the en.json. If you remove it manually, everything works fine.
https://gitlab.com/foundrynet/foundryvtt/-/issues/4710

**Comment by eclarke12** [comment]
Thanks @Vagor96 !
