### ISSUE TITLE
Make Concentrator remove concentration if the DC is not met.

### ISSUE THREAD

**Issue by szefo09** [death-save/combat-utility-belt#451]
**Is your feature request related to a problem? Please describe.**
It's a QoL kind of change, because as a user, I would expect the concentration to be removed after I make the roll.

**Describe the solution you'd like**
I would expect the roll to check if the DC was met or not.
So something like this in the concentrator.js` _displayPrompt` method would be nice (requires some additional passed parameters.)
```
                    callback: e => {
                        actor.rollAbilitySave(ability).then(result=>{
                            if(result.total>=dc){
                                return;
                            }
                            if(tokenId){
                                let token = canvas.tokens.get(tokenId)
                                if(token)
                                {
                                 return Concentrator._processFailDC(token);
                                }
                            }
                            return Concentrator._processFailDC(actor);
                    });
                    }
```

**Describe alternatives you've considered**
I assume there could be another check(?) if the user wants this functionality.

**Comment by eclarke12** [comment]
I could've sworn this was duplicate, but I can't find the issue. This is a long requested feature, but I'm not considering any additional scope in CUB at this time.

**Comment by depili** [comment]
Having the concentration status be removed on failure would be really really really useful.

**Comment by ThingsCouldGetDicey** [comment]
upvote

**Comment by millieloop** [comment]
Yep, defo agree. To be honest, I thought that was how it worked. I wonder how often I've accidentally kept it when I should have lost the concentration!

**Comment by szefo09** [comment]
I was able to play around enough with the CUB code to assign concentration that depends on the duration of the spell, and when DC is not met or the character is at 0 HP, it removes concentration and all other effects that were applied from the same origin as the concentration. For me, this is pretty much how I wish CUB worked.

https://user-images.githubusercontent.com/37833135/105163119-c571ae00-5b13-11eb-89c7-7312730a2478.mp4

**Comment by eclarke12** [comment]
@glimmbo you may want to review the above as part of your Concentrator redesign!

**Comment by Shuggaloaf** [comment]
@szefo09 Seems there's no movement on this unfortunately. 

Would you be willing to share your code on how you did this? Or better yet, perhaps fork this and distribute your own version? 

Your video showcases exactly how this should work and I know a lot of people would be very happy to get a copy working the way you've coded it to.

**Comment by eclarke12** [comment]
> I was able to play around enough with the CUB code to assign concentration that depends on the duration of the spell, and when DC is not met or the character is at 0 HP, it removes concentration and all other effects that were applied from the same origin as the concentration. For me, this is pretty much how I wish CUB worked.
> 
>  CUB.Concentration.example.mp4

I welcome PRs for this kind of thing!

**Comment by szefo09** [comment]
@Shuggaloaf @eclarke12 
I made a fork of this repo and did commit my wonky implementation. There are certainly better ways of doing this, so I’ll not create a PR, but you can check the changes (mostly to the concentrator.js file) that I made to demo it. If errational likes my implementation, they are welcome to add it :)
