### ISSUE TITLE
Conditions added by macro do not properly create a chat message.

### ISSUE THREAD

**Issue by SalieriC** [death-save/combat-utility-belt#452]
**Describe the bug**
Conditions applied by token.toggleEffect("imageFilePath") do not create a chat message, Status effects applied by token.toggleOverlay("imageFilePath") do create a chat message but it is buggy: 
![image](https://user-images.githubusercontent.com/1230041/102770257-1d39bf80-4384-11eb-88ac-52f8b5f0968d.png)

**To Reproduce**
1. Have CUBs Enhanced Conditions Setting "Output to Chat" active.
2. Apply a condition using token.toggleEffect("imageFilePath") or token.toggleOverlay("imageFilePath") via macro.

**Expected behavior**
It should output the condion as set up in the conditionlab.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.9
 - Game System / Version: SWADE
 - CUB Version 1.3.8
 - Browser: Foundry Software
 - OS: Windows

**Additional context**
Possibly related to #367.

**Comment by eclarke12** [comment]
@SalieriC I don't think this is valid anymore. Conditions should be added via `game.cub.addCondition`

**Comment by SalieriC** [comment]
Absolutely right. Been using this for a while and forgot about this ticket, I'm sorry.
