### ISSUE TITLE
Pass Actor information to Triggler Macro executions

### ISSUE THREAD

**Issue by BoltsJ** [death-save/combat-utility-belt#453]
**Is your feature request related to a problem? Please describe.**
When using the trigger feature to automatically run macros, there's no reliable way to test which actor set off the trigger.

**Describe the solution you'd like**
Setting a variable with for example the actor id, and possibly other vars with other relevant information such as the value of the triggering attribute.

**Describe alternatives you've considered**
Currently The macro is using the selected token, but this means that the macro fails if run from the actor sheet with no token selected.

**Comment by eclarke12** [comment]
Unfortunately macros currently do not take any input when executed. I've created this issue on the official Foundry issue board to resolve this:
https://gitlab.com/foundrynet/foundryvtt/-/issues/4588

**Comment by eclarke12** [comment]
Foundry issue https://gitlab.com/foundrynet/foundryvtt/-/issues/4588 was closed. Reopening to implement this.

**Comment by eclarke12** [comment]
nevermind I already did this in v1.6.0 /facepalm
