### ISSUE TITLE
Conditions can get stuck so that you can't remove them

### ISSUE THREAD

**Issue by geoidesic** [death-save/combat-utility-belt#456]
**Describe the bug**
I honestly don't know how to reproduce this reliably but it goes something like this. Assign a condition to a token. Assign that token to an Actor while it has a condition. Then go and update your conditions and change the mappings. Now you'll have a condition that can't be removed from the actor.

**To Reproduce**
As above

**Expected behavior**
I don't know but maybe a button that removes all conditions from an actor would solve this problem. As you can see from the screenshot, this actor has two conditions which don't even exist in the conditions list. In this example I've disabled CUB, but even with CUB enabled, those conditions can't be removed.

**Screenshots**
<img width="685" alt="Screenshot 2020-12-26 at 21 54 54" src="https://user-images.githubusercontent.com/4637995/103158313-01d81580-47c5-11eb-9ce4-0cce10ae3d9a.png">

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.9
 - Game System / Version: dnd5e
 - CUB Version 1.3.8
 - Browser: Chrome
 - OS Mac OS X Catalina

**Additional context**
Just to be clear I'll describe it again and a bit more... I installed CUB, then added a bunch of conditions. I then moved my game around a bit from local to TheForge, then to my own hosted server. I also re-mapped CUB conditions several times and at one point I also had 5e conditions installed. These condition icons got stuck on several PC tokens and can't be removed. I've tried everything – deleting the token and re-dragging it out from actors. I've tried disabling all modules, I've tried using the token context menu. I've tried duplicating the actor. I've tried creating a new token and assigning that token to the actor. Nothing works. 
The only work-around I've found is to create a completely new character.

**Comment by dmaneyapanda** [comment]
I also have experienced this same issue.  I have no idea how it happened, but now I have a condition set which I cannot get rid of (and the icon for which does not exist in the current mapping, so I have no idea what it is even signifying).

**Comment by dmaneyapanda** [comment]
This post shows how to remove them: https://www.reddit.com/r/FoundryVTT/comments/jhquz7/unable_to_remove_condition_markers_since_75cub/

**Comment by eclarke12** [comment]
I hadn't ever accounted for a workflow of taking a token and assigning it to a different actor than it originally had. Given the difficulty in repro and the presence of a workaround I'm going to mark this as wontfix for now but I will reassess as the Foundry API evolves.
