### ISSUE TITLE
Combat Utility Belt label shows twice in Game Settings

### ISSUE THREAD

**Issue by tjlanza** [death-save/combat-utility-belt#458]
**Describe the bug**
"Combat Utility Belt" label shows up twice in game settings.

**To Reproduce**
1. Install nothing but CUB.
2. Click on "Game Settings".
3. See "Combat Utility Belt" twice.

**Expected behavior**
It should only show up once.

**Screenshots**
![DnD5E](https://user-images.githubusercontent.com/21128724/103575123-2efc8600-4e9f-11eb-8c33-0e081f299755.PNG)
![CPRed](https://user-images.githubusercontent.com/21128724/103575132-3328a380-4e9f-11eb-9f1e-76f3e1bec86c.png)
![SR5](https://user-images.githubusercontent.com/21128724/103469532-f4c2a580-4d33-11eb-828e-045d9e0d6edd.PNG)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.8
 - Game System / Version: DnD5e - Fifth Edition System 1.2.0, Shadowrun 5th Edition 0.7.7. Cyberpunk RED 0.42,
 - CUB Version 1.3.8
 - Browser Chrome
 - OS Windows 10

**Comment by eclarke12** [comment]
@tjlanza I believe this is caused by another module. You may want to investigate disabling other modules, or just starting your world with only CUB enabled to confirm. Thanks!

**Comment by tjlanza** [comment]
> @tjlanza I believe this is caused by another module. You may want to investigate disabling other modules, or just starting your world with only CUB enabled to confirm. Thanks!

As indicated in the screen shot, there is only one module loaded.

**Comment by eclarke12** [comment]
> > @tjlanza I believe this is caused by another module. You may want to investigate disabling other modules, or just starting your world with only CUB enabled to confirm. Thanks!
> 
> As indicated in the screen shot, there is only one module loaded.

My apology. I've never seen this in dnd5e, but I'll do some more testing based on your comment about which systems are affected.

**Comment by tjlanza** [comment]
I spun up fresh worlds for D&D5E and CPRED to check. I didn't have D&D5E installed at all before adding it to check.

**Comment by fiagewinnt** [comment]
Just came here to look if somebody else reported that problem already. 

It's also happening for me. Created a complete new test world with only CUB enabled and I get the same. 
If I enable PopOut! module as well and pop out the window I even see all the buttons double - see screenshot below.

![image](https://user-images.githubusercontent.com/61601634/103878807-34dcac00-50d7-11eb-8977-fc559c3a93e1.png)

Environment Info (please complete the following information):

Foundry Version: 0.7.8
Game System / Version: DnD5e - Fifth Edition System 1.2.0
CUB Version 1.3.8
Browser Chrome
OS Windows 10

**Comment by eclarke12** [comment]
@tjlanza can you please confirm this is happening on Foundry 079 also?

**Comment by tjlanza** [comment]
> @tjlanza can you please confirm this is happening on Foundry 079 also?

It does not appear to be an issue with FVTT 0.7.9
