### ISSUE TITLE
Encumbrance as an attribute in Triggler

### ISSUE THREAD

**Issue by DFreds** [death-save/combat-utility-belt#464]
**Is your feature request related to a problem? Please describe.**
I would like to support [variant encumbrance](https://5thsrd.org/rules/abilities/strength/#variant-encumbrance) via conditions. Currently, I have no way to trigger a condition based on encumbrance.

**Describe the solution you'd like**
An attribute added to Triggler for encumbrance.

**Describe alternatives you've considered**
Manually applying conditions that include the effects I want

**Comment by eclarke12** [comment]
Duplicate of #364
