### ISSUE TITLE
Award XP not actually awarding XP

### ISSUE THREAD

**Issue by kuchrk24** [death-save/combat-utility-belt#470]
**Describe the bug**
Award XP is not awarding xp on combat end

**To Reproduce**
1. End combat
2. Check award xp and click yes

**Expected behavior**
See a chat log of awarded XP and character xp increased.

**Screenshots**
![awardxp](https://user-images.githubusercontent.com/74018852/106159136-7bf81300-6152-11eb-80f6-327b6c3e6425.gif)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.9
 - Game System / Version: dnd5e 1.2.4
 - CUB Version 1.3.8
 - Browser Brave (Chromium)
 - OS Windows 10

**Additional context**
Honestly not sure what happened as it has worked in other worlds, but I have tried disabling every other module other than CUB and it still does not work. I don't see any console errors when I end combat with Award XP checked. If there is anything else I can provide, let me know.

**Comment by gravagehulk** [comment]
This happens to me as well and seems to be random. I use imported Roll20 modules and I initially blamed it on the imported tokens/actors (which often have other issues in Foundry), but I think there's more to it than that. I have also noticed that when it does work, it calculates incorrectly at times. Even if I make sure that all friendlies are friendly (i.e. summoned creatures, etc) and every creature is marked defeated, the XP calculation seems to be off at times.

**Comment by eclarke12** [comment]
This should be resolved with #527
