### ISSUE TITLE
CUB options in the Settings sidebar tab have a width that doesn't respect the UI 

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#478]
CUB options in the Settings sidebar tab have a width that doesn't respect the UI button width and appear shorter. This triggers OCD in some players/DM. 

![image](https://user-images.githubusercontent.com/4083812/107487785-36ded280-6b8f-11eb-999e-cc1f60e63f5c.png)

**Comment by eclarke12** [comment]
Look... one of CUB's new year's resolutions was to lose some weight OK?! We shouldn't judge CUB for being a little bit skinny!
