### ISSUE TITLE
Award XP not working

### ISSUE THREAD

**Issue by HarryWraith** [death-save/combat-utility-belt#493]
I have enable 'Award XP' and at the end of combat I do get a prompt which a check box asking me if I would like to do so. However, none of the player's XP totals are increasing. 

I am new to this so I accept this could be user error.

Additional info: using midi-qol and TidySheet5E

**Comment by BaklavaBear** [comment]
I am also having the same problem. At the end of combat, I can tick Award XP, but I do not get a chat message nor does any of my PCs XP increase. I have turned off all mods except CUB.

**Comment by zprimal** [comment]
Having the same issue, after combat, the box comes up and I tick the option to award XP, but XP is not awarded. I have made sure there is one unconscious hostile and one conscious PC for this.

**Comment by kuchrk24** [comment]
I created a bug for this as well. I can't seem to find it, but I think in my case it was that I was using Firefox. Tried using a chromium based browser and it worked.

**Comment by zepheris** [comment]
I can also confirm that I'm unable to award XP at the end of a battle. I'm just starting out with Foundry. I did try Chrome (I was using firefox at the time) and nothing changed. Unable to award xp. I assume the defeated monsters need to have the dead flag assigned and HP to 0. I've reviewed the console log and am not finding any errors. I even wiped my foundry install and started with just CUB as the only module.

**Comment by eclarke12** [comment]
> I can also confirm that I'm unable to award XP at the end of a battle. I'm just starting out with Foundry. I did try Chrome (I was using firefox at the time) and nothing changed. Unable to award xp. I assume the defeated monsters need to have the dead flag assigned and HP to 0. I've reviewed the console log and am not finding any errors. I even wiped my foundry install and started with just CUB as the only module.

In order for XP to be awarded you need to have defeated hostile disposition `npc` actors in the tracker and undefeated player-owned actors in the tracker.

**Comment by zepheris** [comment]
> 
> 
> > I can also confirm that I'm unable to award XP at the end of a battle. I'm just starting out with Foundry. I did try Chrome (I was using firefox at the time) and nothing changed. Unable to award xp. I assume the defeated monsters need to have the dead flag assigned and HP to 0. I've reviewed the console log and am not finding any errors. I even wiped my foundry install and started with just CUB as the only module.
> 
> In order for XP to be awarded you need to have defeated hostile disposition `npc` actors in the tracker and undefeated player-owned actors in the tracker.

Running the character when owned by the DM doesn't award XP to the DM owned character? Am I understanding that correctly? It has to be a player owned actor?

**Comment by eclarke12** [comment]
> > > I can also confirm that I'm unable to award XP at the end of a battle. I'm just starting out with Foundry. I did try Chrome (I was using firefox at the time) and nothing changed. Unable to award xp. I assume the defeated monsters need to have the dead flag assigned and HP to 0. I've reviewed the console log and am not finding any errors. I even wiped my foundry install and started with just CUB as the only module.
> > 
> > 
> > In order for XP to be awarded you need to have defeated hostile disposition `npc` actors in the tracker and undefeated player-owned actors in the tracker.
> 
> Running the character when owned by the DM doesn't award XP to the DM owned character? Am I understanding that correctly? It has to be a player owned actor?

There must be at least one player owner of the actor

**Comment by eclarke12** [comment]
Should be resolved in #527
