### ISSUE TITLE
Hide NPC Names throws an error if Image Popout has _related:null

### ISSUE THREAD

**Issue by BadIdeasBureau** [death-save/combat-utility-belt#499]
**Describe the bug**
If an image popout is rendered with _related:null, then hide npc names will try to find _related.entity and will throw an error.

see: https://github.com/BadIdeasBureau/scene-viewer/issues/5

**To Reproduce**
In console, make a new image popout:

`const ip = new ImagePopout("path/to/image",{title:"foo", entity:game.actors.getName("bar")})`
`ip.render(true)`

Constructed ImagePopouts have _related: null unless a uuid is passed into the constructor (which is not required, and may not be desirable in all use cases), so https://github.com/death-save/combat-utility-belt/blob/master/modules/hide-names/hide-npc-names.js#L243 throws an error trying to find `_related.entity`

**Expected behavior**
Handle this gracefully, without throwing an error

**Screenshots**

**Environment Info (please complete the following information):**
Not expected to be environement dependent.
 - Foundry Version: 0.7.9
 - Game System / Version: 1.2.4
 - CUB Version 1.4.0
 - Browser Chrome
 - OS Windows 10
 

**Additional context**
I'm also fixing this on my end for Compendium Scene Viewer (since in this case it does relate to an entity, so I can provide a UUID), but I think it's still worth fixing this edge case on your end.

**Comment by eclarke12** [comment]
this should be resolved with v1.5.0
