### ISSUE TITLE
Condition Lab won't open

### ISSUE THREAD

**Issue by cbgh2021** [death-save/combat-utility-belt#510]
**Describe the bug**
I try to click the condition lab button and nothing works. It used to work just fine.

**To Reproduce**
Doesn't matter if I uninstall the module and reinstall it. nothing seems to get this error fixed.

**Expected behavior**
condition lab should open. :)

**Screenshots**
[https://cdn.discordapp.com/attachments/722566083499786352/837375099681374249/unknown.png](url)

**Environment Info (please complete the following information):**
 - Foundry Version: newest
 - Game System / Version: . dnd5e newest
 - CUB Version: Latest
 - Browser The foundry program
 - OS Windows 10

**Additional context**
This is the error from the console

foundry.js:3780 Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\persistence.js:242:11)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\persistence.js:281:38
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
_handleError @ foundry.js:3780
(anonymous) @ foundry.js:3761
n.onack @ index.js:83
n.onpacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.ondecoded @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
a.add @ index.js:83
n.ondata @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
n.onData @ index.js:83
ws.onmessage @ index.js:83
foundry.js:4481 Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\persistence.js:242:11)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\persistence.js:281:38
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

**Comment by eclarke12** [comment]
This sounds like an issue with your Foundry db/s. You may want to check with the Foundry support to resolve this first.

**Comment by cbgh2021** [comment]
Doing that now. Db/s means? database?

**Comment by eclarke12** [comment]
> Doing that now. Db/s means? database?

That's correct.

**Comment by cbgh2021** [comment]
Their help is 'disable all modules, do you still get the error?'

So, no go there.

**Comment by cbgh2021** [comment]
I followed all of the steps their staff gave me, we wiped the database files.
if I create a new world, and only enable combat utility belt, I can access the lab.
If I edit the current world to only have combat utility belt running, I get the above error.

**Comment by Feu-Secret** [comment]
Same problem as @cbgh2021. Condition Lab not opening 😿

**Comment by cbgh2021** [comment]
This solution does not work for me. 
I've reinstalled foundry, cleared databases and disabled all but combat utility belt.

**Comment by cbgh2021** [comment]
I made a new world and the condition lab opened. But this doesn't solve the problem I have with my massive home brew world that took months to build.
:)

**Comment by cbgh2021** [comment]
PROBLEM FIXED!
No idea what caused the problem still, but what I did was make a new world, copied over all of my files from my old world to the new one.
Why that works?! no idea. but after about 20 hours of fearing that I had lost the ability to use combat utility belt with a massive campaign, I'm glad it's fixed.
