### ISSUE TITLE
Foundry 0.8.x patching progress

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#517]
~~*Please leave your testing findings in the comments below! Information about your setup (Foundry version, system, browser etc are always helpful).*~~

This issue is now being used to track the progress of fixes based on changes from 08x

---

### Dialog spawned on combat end
- [x] Pass
(Pass/Fail notes)

### XP distributed correctly
- [x] Pass
(Pass/Fail notes)

### Auto-set Concentrating condition on spell cast
- [x] Pass
(Pass/Fail notes)

### Output to Chat
- [x] Pass
(Pass/Fail notes)

### Prompt for check on damage
- [x] Pass
~~double prompt~~ token updates now trigger tokenactor update which triggers actor hooks -- removed token hooks

### Notify double-concentration
- [x] Pass
(Pass/Fail notes)

### Condition Lab loads
- [x] Pass
(Pass/Fail notes)

### Game System detected
- [x] Pass
(Pass/Fail notes)

### Macro methods work
- [x] Pass
(Pass/Fail notes)

### Outputs to Chat
- [x] Pass
~~**FAIL: cannot read property `isGM` of undefined**~~
FAIL: overlay conditions fail for unmapped core icons -- record as known issue
note: border around conditions

### Remove default conditions works
- [x] Pass
(Pass/Fail notes)

### Hide NPC names in chat
- [x] Pass
(Pass/Fail notes)

### Hide NPC names in combat tracker
- [x] Pass
names not hidden

### Hide NPC names in combat tracker tooltip
- [x] Pass
names not hidden

### Reroll on Round Change
- [x] Pass
(Pass/Fail notes)

### Detects actor properties
- [x] Pass
(Pass/Fail notes)

### Triggers fire on update
- [ ] Pass
error on remove condition

### Pans on turn
- [x] Pass
(Pass/Fail notes)

### Pan respects GM/player setting
- [x] Pass
(Pass/Fail notes)

### Selects on turn
- [x] Pass
(Pass/Fail notes)

### Select respects GM/player setting
- [x] Pass
(Pass/Fail notes)

### Correctly sets HP when enabled
- [x] Pass
(Pass/Fail notes)

### Edit tracked resource works
- [x] Pass
(Pass/Fail notes)

### Auto Roll Hostile HP correctly rolls when hostile token dropped
- [x] Pass
(Pass/Fail notes)

### Resize effects works
- [x] Pass
(Pass/Fail notes)

**Comment by megahead11** [comment]
Enhanced conditions appears to work, but it appears the output message for it doesn't seem to send.
![Screenshot 2021-05-14 034524](https://user-images.githubusercontent.com/21242682/118260221-db123700-b466-11eb-9c2e-418fc6aa277f.png)

**Comment by eclarke12** [comment]
> Enhanced conditions appears to work, but it appears the output message for it doesn't seem to send (output conditions to chat)
> ![Screenshot 2021-05-14 034524](https://user-images.githubusercontent.com/21242682/118260221-db123700-b466-11eb-9c2e-418fc6aa277f.png)

that's promising, but that's an odd place for it to fail. It's not finding a user for the message it appears.

**Comment by eclarke12** [comment]
I believe I have addressed most of the issues arising from 08x. Will continue testing and release before 086.

**Comment by Th3Rom3** [comment]
> 
> 
> I believe I have addressed most of the issues arising from 08x. Will continue testing and release before 086.

Thank you kind sir =)

**Comment by irbian** [comment]
Don´t know what is happening here:

```
VM10400:8 TypeError: Cannot create property 'combat-utility-belt' on string 'cbICysaEvZnr2dRc'
    at Function._onPreUpdateToken (enhanced-conditions.js:97)
    at signal.js:130
    at Function._call (eval at <anonymous> (libWrapper-errors.js:249), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at BabeleClientDatabaseBackend._preUpdateDocumentArray (foundry.js:8776)
    at async BabeleClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8714)
    at async Function.updateDocuments (document.mjs:365)
    at async TokenDocument.update (document.mjs:447)
```

FVTT 0.8.6
3.5srd

**Comment by eclarke12** [comment]
> Don´t know what is happening here:
> 
> ```
> VM10400:8 TypeError: Cannot create property 'combat-utility-belt' on string 'cbICysaEvZnr2dRc'
>     at Function._onPreUpdateToken (enhanced-conditions.js:97)
>     at signal.js:130
>     at Function._call (eval at <anonymous> (libWrapper-errors.js:249), <anonymous>:4:14)
>     at Function.call (foundry.js:179)
>     at BabeleClientDatabaseBackend._preUpdateDocumentArray (foundry.js:8776)
>     at async BabeleClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8714)
>     at async Function.updateDocuments (document.mjs:365)
>     at async TokenDocument.update (document.mjs:447)
> ```
> 
> FVTT 0.8.6
> 3.5srd

CUB v1.4.0 is not compatible with FVTT 0.8.6. Please retest with CUB 1.5.0 and open a new issue if you are still encountering that error. Thanks!
