### ISSUE TITLE
Token select is not working

### ISSUE THREAD

**Issue by franckflo** [death-save/combat-utility-belt#519]
**Describe the bug**
Even with Pan/Select functions enabled in CUB settings, tokens are not selected during combat when their turn comes. 

**To Reproduce**
1. As a GM and using browser, select several tokens (NPCs and PCs) and start an encounter.
2. Move initiative forward
3. The canvas pans to the new initiative token, but it is not selected. 

**Expected behavior**
In addition to panning, the new initiative token should be selected without clicking on it.

**Screenshots**
See attached, showing settings I used for CUB select/pan feature

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.9
 - Game System / Version:  dnd5e 1.2.4
 - CUB Version 1.4.0
 - Browser Brave
 - OS Windows 10
 - 
**Additional context**
I used find the culprit to isolate CUB. With only CUB enabled, the selection is still not working, so I don't think this is a conflict with another moduel.

**Comment by eclarke12** [comment]
please provide a screenshot of your CUBputer - Pan/Select settings. Also please test in a different browser. Thanks!

**Comment by franckflo** [comment]
I think I figured out what caused that: a conflict with the Macro Folders module.
