### ISSUE TITLE
Cannot right-click tokens in PF2e with Enhanced Conditions active

### ISSUE THREAD

**Issue by yorkshirelandscape** [death-save/combat-utility-belt#520]
With Condition Lab enabled and a custom condition created, right clicking on a token no longer has any effect. It will work initially, but if you log out of the session and log back in, right clicking will have ceased to work. 

1. Install CUB and enable Condition Lab.
2. Within Condition Lab, add a new condition of either System - Custom or Other - Imported mapping type (I cannot confirm this behavior with System - Inferred, because clicking Add Row does nothing). No special settings. I just chose a name and icon.
3. Save the mapping and close Condition Lab.
4. Log out of the session, then log back in.
5. Right click on a token. Nothing will happen.

**Expected behavior**
Right-clicking should allow me to open up the condition selector, which would let me use my new condition. Since nothing happens when I right-click, I cannot.

**Environment Info:**
 - Foundry Version: 0.7.9
 - Game System / Version: 1.13.1.5391
 - CUB Version: 1.4.0
 - Browser: Google Chrome
 - OS: Windows 10

**Additional context**
It's worth noting that, even when you right click on a token BEFORE logging out and back in, the new condition does not appear in the condition selector.

**Comment by yorkshirelandscape** [comment]
I just did what I should have done initially, which is disable all the modules I had running. No change.

**Comment by eclarke12** [comment]
> I just did what I should have done initially, which is disable all the modules I had running. No change.

I'm assuming you mean all modules OTHER than CUB?

I'm not surprised CUB is experiencing issues with PF2e. It is something I would like to solve in a meaningful fashion, but that team is doing some awesome automation stuff that makes it a bit more complicated.

**Comment by yorkshirelandscape** [comment]
> I'm assuming you mean all modules OTHER than CUB?

Well, yes. Other than CUB. :)

**Comment by eclarke12** [comment]
Can you please clarify which system this is occurring with? based on the version number I'm guessing pf2e?

**Comment by yorkshirelandscape** [comment]
Ahh, yes. I apologize. This is PF2e. We’d discussed it in the Discord, but I forgot to mention it in the ticket.

**Comment by eclarke12** [comment]
Due to the complexity/custom nature of PF2e Status Effects I am no longer supporting it in Enhanced Conditions.
