### ISSUE TITLE
Ironclaw 2e support

### ISSUE THREAD

**Issue by Hertzila** [death-save/combat-utility-belt#522]
Hello. You suggested that I open an issue here for the Ironclaw 2e support. So:  

The system identifier is "ironclaw2e", and the condition map is attached. The conditions are pretty central to the system, since the combat is based entirely on them, rather than a HP system.  
The system's page is here: https://foundryvtt.com/packages/ironclaw2e  

The condition map zipped, because GitHub doesn't like raw json files for whatever reason: [ironclaw2e.zip](https://github.com/death-save/combat-utility-belt/files/6542453/ironclaw2e.zip)

**Comment by eclarke12** [comment]
hi @Hertzila can you please provide the following info:

- `health` attribute name (ie. the attribute used to indicate health on an actor)
- `initiative` attribute name (ie. the attribute used to indicate initiative on an actor)

**Comment by Hertzila** [comment]
Hello there. Short answer: There aren't any.

 - Health: The system is based entirely on conditions. There is no health attribute, only a descending order of worse conditions that affect the character based on the damage of the attack. It can't really be modeled by a health attribute, since the conditions can be healed out of order.
 - Initiative: There is no attribute for initiative in standard rules. A variant rule exists where it is based entirely on a dice roll, but by default, it's based entirely on sides and who started the fight. Eg. If the players waltz into an ambush, the enemy NPC's all go first, followed by the player characters and any allied NPC's they might have.

**Comment by eclarke12** [comment]
> Hello there. Short answer: There aren't any.
> 
> * Health: The system is based entirely on conditions. There is no health attribute, only a descending order of worse conditions that affect the character based on the damage of the attack. It can't really be modeled by a health attribute, since the conditions can be healed out of order.
> * Initiative: There is no attribute for initiative in standard rules. A variant rule exists where it is based entirely on a dice roll, but by default, it's based entirely on sides and who started the fight. Eg. If the players waltz into an ambush, the enemy NPC's all go first, followed by the player characters and any allied NPC's they might have.

Thanks, I will update CUB to correctly identify the system and include a standard condition map.
