### ISSUE TITLE
Triggler throws error when loading a scene with no tokens

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#534]
![image](https://user-images.githubusercontent.com/42503461/120549598-a976f680-c3a8-11eb-98b7-84c1f5ad7212.png)
reported by @aeristoka

**Comment by Aeristoka** [comment]
You're welcome to test on my server. I haven't yet found how to reliably trigger this, but it spams a lot.

**Comment by eclarke12** [comment]
> You're welcome to test on my server. I haven't yet found how to reliably trigger this, but it spams a lot.

Can you please dm me a link? I cannot repro. Thanks!

**Comment by strongpauly** [comment]
I see this too on 0.8.6.
```
triggler.js:74 Uncaught (in promise) TypeError: Cannot read property 'hasPlayerOwner' of null
    at Function._processUpdate (modules/combat-utility-belt/modules/triggler/triggler.js:74)
    at Function._onUpdateToken (modules/combat-utility-belt/modules/triggler/triggler.js:287)
    at modules/combat-utility-belt/modules/signal.js:136
    at Function._call (eval at <anonymous> (modules/lib-wrapper/lib-wrapper.js:1), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8866)
    at foundry.js:8836
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8836)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8725)
    at async Function.updateDocuments (common/abstract/document.mjs:365)
```

**Comment by eclarke12** [comment]
I notice both errors have lib-wrapper in the stack. I'm not sure if that's a clue or a red herring. At the start of the stack it is calling `updateDocuments` then `updateEmbeddedDocuments` which means some action in Foundry is updating tokens.

@Aeristoka I'll try to jump into your server on the weekend and look thx

**Comment by Aeristoka** [comment]
> I notice both errors have lib-wrapper in the stack. I'm not sure if that's a clue or a red herring. At the start of the stack it is calling `updateDocuments` then `updateEmbeddedDocuments` which means some action in Foundry is updating tokens.
> 
> @Aeristoka I'll try to jump into your server on the weekend and look thx

Let me send you a new invite, I backed my main server back down to 0.7.10 because of a FoundryVTT breaking bug with hiding extra content in a RollMessage

**Comment by eclarke12** [comment]
> I see this too on `0.8.6`.
> 
> ```
> triggler.js:74 Uncaught (in promise) TypeError: Cannot read property 'hasPlayerOwner' of null
>     at Function._processUpdate (modules/combat-utility-belt/modules/triggler/triggler.js:74)
>     at Function._onUpdateToken (modules/combat-utility-belt/modules/triggler/triggler.js:287)
>     at modules/combat-utility-belt/modules/signal.js:136
>     at Function._call (eval at <anonymous> (modules/lib-wrapper/lib-wrapper.js:1), <anonymous>:4:14)
>     at Function.callAll (foundry.js:153)
>     at ClientDatabaseBackend.callback (foundry.js:8866)
>     at foundry.js:8836
>     at Array.map (<anonymous>)
>     at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8836)
>     at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8725)
>     at async Function.updateDocuments (common/abstract/document.mjs:365)
> ```

Do you use Multi-Level Tokens by chance? I think it's possible MLT is sending some update that is causing the `token.actor` property to be null which then causes Triggler to choke on a certain check. I will fix the logic in Triggler, but if you use MLT you may want to refer them to this issue.

**Comment by Aeristoka** [comment]
> > I see this too on `0.8.6`.
> > ```
> > triggler.js:74 Uncaught (in promise) TypeError: Cannot read property 'hasPlayerOwner' of null
> >     at Function._processUpdate (modules/combat-utility-belt/modules/triggler/triggler.js:74)
> >     at Function._onUpdateToken (modules/combat-utility-belt/modules/triggler/triggler.js:287)
> >     at modules/combat-utility-belt/modules/signal.js:136
> >     at Function._call (eval at <anonymous> (modules/lib-wrapper/lib-wrapper.js:1), <anonymous>:4:14)
> >     at Function.callAll (foundry.js:153)
> >     at ClientDatabaseBackend.callback (foundry.js:8866)
> >     at foundry.js:8836
> >     at Array.map (<anonymous>)
> >     at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8836)
> >     at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8725)
> >     at async Function.updateDocuments (common/abstract/document.mjs:365)
> > ```
> 
> Do you use Multi-Level Tokens by chance? I think it's possible MLT is sending some update that is causing the `token.actor` property to be null which then causes Triggler to choke on a certain check. I will fix the logic in Triggler, but if you use MLT you may want to refer them to this issue.

I can throw the issue their way too, do you have more of the specifics about where you saw what they were doing?

**Comment by eclarke12** [comment]
> > > I see this too on `0.8.6`.
> > > ```
> > > triggler.js:74 Uncaught (in promise) TypeError: Cannot read property 'hasPlayerOwner' of null
> > >     at Function._processUpdate (modules/combat-utility-belt/modules/triggler/triggler.js:74)
> > >     at Function._onUpdateToken (modules/combat-utility-belt/modules/triggler/triggler.js:287)
> > >     at modules/combat-utility-belt/modules/signal.js:136
> > >     at Function._call (eval at <anonymous> (modules/lib-wrapper/lib-wrapper.js:1), <anonymous>:4:14)
> > >     at Function.callAll (foundry.js:153)
> > >     at ClientDatabaseBackend.callback (foundry.js:8866)
> > >     at foundry.js:8836
> > >     at Array.map (<anonymous>)
> > >     at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8836)
> > >     at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8725)
> > >     at async Function.updateDocuments (common/abstract/document.mjs:365)
> > > ```
> > 
> > 
> > Do you use Multi-Level Tokens by chance? I think it's possible MLT is sending some update that is causing the `token.actor` property to be null which then causes Triggler to choke on a certain check. I will fix the logic in Triggler, but if you use MLT you may want to refer them to this issue.
> 
> I can throw the issue their way too, do you have more of the specifics about where you saw what they were doing?
@grandseiken 
I don't have good repro but it seems to be related to line 715 in `multileveltoken.js` https://github.com/grandseiken/foundryvtt-multilevel-tokens/blob/fdb4c14e51b040084171de287daa79d6e1254186/multilevel.js#L715. It seems to then send a token instance into the update callstack that has no actor (possibly something to with being a cloned token or???)

Regardless if it is the culprit, Triggler shouldn't be tripped up by it any more.

**Comment by strongpauly** [comment]
I am using MLT too.
