### ISSUE TITLE
Conditions in a compendium outputed to the chat do not open the journal entry

### ISSUE THREAD

**Issue by spirritus** [death-save/combat-utility-belt#536]
**Describe the bug**
Conditions in a compendium outputed to the chat do not open the journal entry (dnd5e).

**To Reproduce**
1. Open Condition Lab, set mapping Type to System-Custom
2. Set the blinded output to. "Journal (C) -> Conditions (D6D5e) -> blinded
3. Save mapping
4. Set the condition on a token.
5. Click on blinded in the chat, nothing happens.

The condition card does work when you import the compendium into your world and reference your local journal. However, this did work with foundry 0.7.x. This feature not workin is new in foundry 0.8.6.

**Expected behavior**
The journal entry should open.

**Environment Info (please complete the following information):**
 - Foundry Version: [0.8.6]
 - Game System / Version: [dnd5e 1.3.3]
 - CUB Version [1.5.0]
 - Browser [firefox]
 - OS [Windows 7]

**Comment by eclarke12** [comment]
Fixed in upcoming patch v1.5.1
