### ISSUE TITLE
Condition Lab not working as intended?

### ISSUE THREAD

**Issue by OGTatarius** [death-save/combat-utility-belt#539]
Describe the bug
Using the Other/imported feature, the Active effect Config does not open.
Also (not sure if it is related) when I change the context of a condition to link to a compendium (JournaL(C);Rules (SRD); <scroll to context of options here>) it does not want to save the "scroll to context of options here" part, thus I can't link a condition (for popping up in chat) to a compendium describing what that condition does. 

edit: So it will save the entry but always defaults to the 1st entry in a list (for example, Journal(C);Conditions (D&D5e); always points to blinded regardless of choice
I looked at the json and then looked at the elements in the debug console and noticed all the id's were "undefined" instead of their values. not sure why? do they need a "-" in front of them or something?

To Reproduce

Click on hand (Active Effect Config)
Nothing happens

Change Compendium pointer to look at different journal/item entry
Click Save Mapping
Nothing happen (close and come back, options not saved)

Expected behavior
Active Effects menu opens (I downloaded 8.6, never ran other version as I am new to foundry, seen this menu from youtube videos describing how to use)

Should save context of chosen compendium

Environment Info (please complete the following information):

Foundry Version: 0.8.6	CUB Version v1.5.0	Browser Chrome	OS Windows 10
Additional context

**Comment by Turqueso** [comment]
About the active effect config https://github.com/death-save/combat-utility-belt/issues/526

**Comment by roi007leaf** [comment]
"Change Compendium pointer to look at different journal/item entry
Click Save Mapping
Nothing happen (close and come back, options not saved)"
+1 for that, happens to me as well, nothing in console or any error appear

**Comment by eclarke12** [comment]
Please try again with v1.6 and report back

**Comment by eclarke12** [comment]
Reopen if still occurring in v1.6.x
