### ISSUE TITLE
Cannot access Condition Effects tab after the update.

### ISSUE THREAD

**Issue by uLotUu** [death-save/combat-utility-belt#541]
**Describe the bug**
Like Described in the title. I can open "Condition Lab" and change Icons for my conditions, but I cannot edit active effects on them.

**To Reproduce**
1. Go to 'Condition Lab'
2. Click on 'active effects of any condition'
3. Nothing happens.

**Environment Info (please complete the following information):**
 - Foundry Version: [0.8.6]
 - Game System / Version: [DND5e]
 - CUB v1.5.0
 - Browser - Chrome
 - OS [Windows 10]

**Additional context**

**Comment by buttonpushertv** [comment]
It happens for me on FVTT 0.8.6 running via node.js on a Pi. It throws errors to console - something about `testuser` and then an `undefined` error whenever AE buttons are clicked.

**Comment by eclarke12** [comment]
Duplicate of #526
