### ISSUE TITLE
Cub does not remove linked conditions after the "parent" condition is removed.

### ISSUE THREAD

**Issue by uLotUu** [death-save/combat-utility-belt#542]
**Describe the bug**
Before the CUB v1.5.0 when a Condition (unconscious for example) applied another condition (incapacitated in this example) when the "parent" condition was removed, any linked condition was also removed. After 1.5.0 when "parent" is removed (unconscious ) other conditions applied are not (so incapacitated stays on an actor). That is also true for macros like Token Magic FX - in the previous version the effect was linked with a condition that triggered it. Now you have to remove it manually. 

**To Reproduce**
1. Go to 'Condition Lab'
2. Go to 'Active Effect of any condition [called "parent" from now on]'
3. Add "macro.CUB" and select any other condition
4. Add the "parent" condition to any actor. Both parent and the condition from macro.Cub are applied.
5. Remove the "parent" condition.
6. Condition(s) from macro.Cub are still active (same is true for macro.tokenMagic).

**Expected behavior**
Any linked condition to a "parent" should be removed along with it. Worked like that before the 1.5.0 and Foundry 0.8.x

**Environment Info (please complete the following information):**
 - Foundry Version: [0.8.6]
 - Game System / Version: [DND 5e 1.3.3]
 - CUB Version [1.5.0]
 - Browser [chrome]
 - OS [Windows 10]

Update 06.11.2021

The problem seems to be with DAE not CUB

**Comment by eclarke12** [comment]
It sounds like this was related to DAE
