### ISSUE TITLE
Triggler throws an error when it encounters a token with no associated actor

### ISSUE THREAD

**Issue by BadIdeasBureau** [death-save/combat-utility-belt#553]
**Describe the bug**
Triggler throws a lot of errors on startup.  With a bit of testing, this corresponds to the number of tokens in my world for which actor === null (i..e where the base actor has been deleted)

**To Reproduce**
1. Drag a token onto the map
2. Delete the associated actor from the actors tab
3. Create a trigger which would check that token
4. Open console

**Expected behavior**
No error is thrown - function aborts gracefully if token.actor === null

**Screenshots**
![image](https://user-images.githubusercontent.com/36359784/122447428-a0d31280-cf9b-11eb-8143-20518beaec92.png)

**Environment Info (please complete the following information):**
 - Foundry Version: . 0.8.6
 - Game System / Version: dnd5e 1.3.5
 - CUB Version 1.5.0
 - Browser Chrome
 - OS Windows 10

**Comment by eclarke12** [comment]
This mentions 1.5.0, but did you mean 1.6.0? If not, please  try 1.6 and let me know.

**Comment by BadIdeasBureau** [comment]
Yeah, I'd just missed the update, sorry!
