### ISSUE TITLE
Pan to token fails for players on 0.8.7 (works fine for GM)

### ISSUE THREAD

**Issue by chklein1** [death-save/combat-utility-belt#557]
When setting Pan Players to Owner or All, owned player tokens do not pan for players when their turn comes up. Panning does work as expected for the GM. Select/Deselect works as expected for both players and GM.

**To Reproduce**
1. Enable Pan Players (example configuration shown below for Owner setting)
2. Create an encounter including a player's token
3. Advance to that player's token's turn

**Expected behavior**
Pan to that player's token

**Screenshots**
![image](https://user-images.githubusercontent.com/85462739/122488984-839a4600-cf93-11eb-96d4-d3dda350becb.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.7
 - Game System / Version: dnd5e 1.3.5
 - CUB Version: 1.6.0
 - Browser: Edge, Chrome
 - OS: Windows 10

**Comment by eclarke12** [comment]
Resolved in #584
