### ISSUE TITLE
Condition Lab failing to render with SFRPG system

### ISSUE THREAD

**Issue by agentnos** [death-save/combat-utility-belt#560]
Simply that, the window for condition lab fails to open. Have tried with no other modules installed and that hasn't changed anything. It's worked on other worlds with the same and different systems installed.

**To Reproduce**
I couldn't tell you how to reproduce, it works on some worlds but not others.

**Expected behavior**
The Condition Lab window is meant to render.

**Screenshots**
![image](https://user-images.githubusercontent.com/6649313/122588973-9bd39900-d057-11eb-8485-26ba81c806e0.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.7
 - Game System / Version: SFRPG 0.11.3
 - CUB Version: 1.6.0
 - Browser: Foundry App
 - OS: Windows 10

Again as I've said, the condition lab opens up on my test world that has the same system running. I've uninstalled and re-installed CUB multiple times, but it doesn't change anything.

**Comment by eclarke12** [comment]
have you tried with libwrapper disabled?

**Comment by agentnos** [comment]
I have, I tried it with all of the modules disabled apart from CUB. But it works on other worlds with it enabled and on the world I'm having this issue, the Triggler window opens, as well as the cubputer, but not the Conditions Lab

**Comment by eclarke12** [comment]
Based on the error in the original comment it appears it was unable to create the condition map. It looks like there's an incompatibility between CUB and Starfinder.

**Comment by eclarke12** [comment]
As a workaround you can try the following:
1. Disable the default status effects under CUBputer > Enhanced Conditions
2. Open Condition Lab
3. Build a mapping from scratch
4. Save the Condition Lab
This will allow CUB to read the conditions.

**Comment by eclarke12** [comment]
Removed compatibility with SFRPG and other systems that use simple status icons in #584 
Opened #580 to reassess this decision in the future
