### ISSUE TITLE
Condition Lab not importing Active Effects

### ISSUE THREAD

**Issue by M0nk3yy** [death-save/combat-utility-belt#564]
**The Bug:**

The Condition Lab export json contains Active Effects, but not are present after importing into a new world. 

**Environment Info:**

 - Foundry Version: 0.8.7
 - System Version: 5e 1.3.5
 - CUB Version: 1.6.0

**Comment by rodrigoistalindir** [comment]
Experiencing the same issue.  If you start from blank you can see it actually does import and create the entries with the correct title and order, but the underlying effects are missing.

**Comment by gravagehulk** [comment]
I can also confirm this issue. I tried exporting/importing multiple times. None of my active effects are coming in. It's a serious pain to recode them each time I start a new World.

**Comment by miromonti** [comment]
This issue is true with me too.

- Foundry 0.8.8
- D&D53 1.3.6
- CUB 1.6.0

**Comment by Altrix1** [comment]
Fix it please

**Comment by gravagehulk** [comment]
I was able to get this working again myself by following the advice of RufusTiki from an earlier issue that was closed:

![image](https://user-images.githubusercontent.com/69117052/126396506-f708bd05-f4bf-4821-ae95-498591a7f27f.png)

**Comment by stevengorrell** [comment]
I am also experiencing this issue. imports are not bringing in the active effects.

**Comment by eclarke12** [comment]
Fixed in the upcoming 1.6.1 release.

**Comment by eclarke12** [comment]
Resolved bt #584
