### ISSUE TITLE
"Ignore Self? " Auras option not working in Condition Lab

### ISSUE THREAD

**Issue by yahavatar** [death-save/combat-utility-belt#565]
**Describe the bug**
When adding an effect in Condition Lab, on the Auras page, the checkbox for "Ignore self?" does not seem to do anything.

**To Reproduce**
1. Go to Auras tab
2. Set a radius
3. Choose Enemy for target
4. Check "Ignore self?"

![image](https://user-images.githubusercontent.com/780527/122797733-cb6be680-d28d-11eb-9b19-b45bed62c1d5.png)

I had setup a simple Effect:

![image](https://user-images.githubusercontent.com/780527/122797804-dd4d8980-d28d-11eb-9543-ad93190c0d96.png)

**Expected behavior**
I would expect ONLY the enemy to get the glow effect, but both the player token and the enemy token get the glow:

![image](https://user-images.githubusercontent.com/780527/122797901-f9512b00-d28d-11eb-882d-d4ec06ae5da9.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.7
 - Game System / Version: [e.g. dnd5e 1.3.5]
 - CUB Version [e.g. 1.6.0]
 - Browser [e.g. Firefox, Chrome]
 - OS [e.g. Windows 10]

**Additional context**

**Comment by eclarke12** [comment]
Auras are not part of core/CUB
