### ISSUE TITLE
Rolled monster HP not being hidden from Players

### ISSUE THREAD

**Issue by Tatonker** [death-save/combat-utility-belt#567]
**Describe the bug**
Monster HP generated by dice rolls are being shown to players

**To Reproduce**
1. Go to "CUBPuter - Misc Token"  
2. Check "Enable Auto roll Hostile Token HP" and "Hide Automatic HP Roll"
3. Drag monster from the Actor side bar to the scene
4. HP rolls are shown to GM and to the players.

**Expected behavior**
Monster HP rolls remain private and not shown to players

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.8
 - Game System / Version: dnd5e 1.3.6
 - CUB Version: 1.6.0
 - Browser: Chrome
 - OS: Windows 10

![CUB settings](https://user-images.githubusercontent.com/70360365/123855182-6e4ae300-d8d4-11eb-8e8c-242a6d221b36.PNG)

**Additional context**
Checked using Find the Culprit and only CUB active and the issue persist (see second screenshot which is from a player's login).

![Player chat window](https://user-images.githubusercontent.com/70360365/123855427-c386f480-d8d4-11eb-8f34-6a1c40eb8632.PNG)

Changing to Private GM roll hides the roll when dropping a new token to the scene.

Verified by Mythano on the Foundry discord.
![Capture](https://user-images.githubusercontent.com/70360365/123856867-73a92d00-d8d6-11eb-9d1b-25645977dafe.PNG)

**Comment by BlackMoons** [comment]
Seems to hide rolls if you set your roll mode to other then public when the setting is enabled. But IMO it should hide them always if that setting is enabled. 

However, it does not hide the roll *sound* and my PC's now know something is spawning for them any time they hear roll sounds.

**Comment by eclarke12** [comment]
> Seems to hide rolls if you set your roll mode to other then public when the setting is enabled. But IMO it should hide them always if that setting is enabled.
> 
> However, it does not hide the roll _sound_ and my PC's now know something is spawning for them any time they hear roll sounds.

Did you confirm other (eg. native) hidden rolls do not generate a roll sound? In the past all rolls generated a sound... I'm pretty sure CUB is just creating a new Roll and marking it hidden, which should perform the same as the native functionality 🤔 but I can't confirm off hand

**Comment by BlackMoons** [comment]
> Did you confirm other (eg. native) hidden rolls do not generate a roll sound? In the past all rolls generated a sound... I'm pretty sure CUB is just creating a new Roll and marking it hidden, which should perform the same as the native functionality thinking but I can't confirm off hand

Nope. didn't confirm but however it decides to come up with the roll, I would REALLY like my players not to hear me placing down NPC's for a surprise attack, or adding reinforcements, etc. Kinda makes it a deal killer for the feature.

**Comment by BlackMoons** [comment]
Did just check now, apparnetly players can hear any roll the GM makes via the standard /roll command. Dunno why, that is just silly.

**Comment by eclarke12** [comment]
> Did just check now, apparnetly players can hear any roll the GM makes via the standard /roll command. Dunno why, that is just silly.

I'm going to close this issue and I suggest you open one in the official Foundry Issue log to get an option to hide GM rolls. There might already be a module that does it!

**Comment by BlackMoons** [comment]
I asked, and they said they where 'just trying to replicate a tabletop' and nobody could suggest a module that muted GM rolls.

**Comment by eclarke12** [comment]
> I asked, and they said they where 'just trying to replicate a tabletop' and nobody could suggest a module that muted GM rolls.

I can't remember if there's an issue with it right now, but Maestro has an option to disable roll sounds. You can log an issue there if you'd like to request only GM rolls be muted (as an example)
