### ISSUE TITLE
Sorting options in the Conditions lab

### ISSUE THREAD

**Issue by Nedrapter** [death-save/combat-utility-belt#569]
**Is your feature request related to a problem? Please describe.**
Adding conditions in the lab simply adds on the end, making a confusing list over the time for the players.

**Describe the solution you'd like**
A sorting option, alphabetically or otherwise.

**Describe alternatives you've considered**
Manually ordering each one of them is REALLY a pain.

**Comment by eclarke12** [comment]
I believe in the last release I mentioned that I would tackle better sorting in the future. It's just something that takes more effort than you'd think to get right :)

**Comment by Nedrapter** [comment]
Any updates on this? The more I use the module, the more I'd appreciate this to be a thing! :D
