### ISSUE TITLE
Bad interaction with "Combat Numbers" mod

### ISSUE THREAD

**Issue by M0nk3yy** [death-save/combat-utility-belt#572]
Versions: Foundry, 5e, Modules all latest stable.

If Combat Utility Belt is used to automate a status effect like "bloodied" at 50% HP using Triggler, an error can be encountered when "Combat Numbers" module is active. The error occurs the actor is healed, removing the wounded condition. This also occurs when an actor with "Dead" or "Unconscious" effects are healed, and those status effects are removed. Error screenshot below:

![image](https://user-images.githubusercontent.com/66137312/125168890-9c1b0c00-e19f-11eb-9c1e-676ec317bab2.png)

![image](https://user-images.githubusercontent.com/66137312/125168877-81489780-e19f-11eb-86fd-9622c5d452d1.png)

**Comment by megahead11** [comment]
This bug may actually be related to an issue with 5e's system and its active effects. 
https://gitlab.com/foundrynet/dnd5e/-/issues/1194

**Comment by eclarke12** [comment]
I believe this was the "ghost active effects" bug as mentioned by @megahead11 but is actually a core issue:https://gitlab.com/foundrynet/foundryvtt/-/issues/5312
