### ISSUE TITLE
updateActor hook bug causes duplicate Triggler Trigger executions

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-utility-belt#573]
caused by: https://gitlab.com/foundrynet/foundryvtt/-/issues/5600

~~It seems both the Token and Actor triggers are processed
https://discord.com/channels/751505150862164129/751602144414531706/863496327156858920~~

**Comment by eclarke12** [comment]
caused by: https://gitlab.com/foundrynet/foundryvtt/-/issues/5600

**Comment by rbl047** [comment]
Same here. Double concentrator check windows appears. If I use "Health Monitor" module, it also shows double health change in the chat. It seems to be a Foundry version issue as stated above.

**Comment by eclarke12** [comment]
Resolved with Foundry 0.8.9
