### ISSUE TITLE
First player is not panned to when Begin Combat is clicked.

### ISSUE THREAD

**Issue by thraxst** [death-save/combat-utility-belt#575]
**Describe the bug**
When starting combat it does not pan to the first player in initiative all the time. See this consistently when initiative rolls are entered manually. 

**To Reproduce**
1. Enter a player and NPC into combat.
2. Manually enter each initiative via right click -> Update Combatant
3. Press Begin Combat
4. Camera does not pan

**Expected behavior**
The camera should pan to the first player in combat

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.8
 - Game System / Version: dnd5e 1.3.6
 - CUB Version 1.6.0
 - Browser Chrome and Firefox
 - OS Windows 10

**Comment by eclarke12** [comment]
Please advise if this is still an issue in with v1.6.1

**Comment by thraxst** [comment]
Yeah, it is still an issue, seems like the options object is not fully setup at the first turn of the first round of combat.
![image](https://user-images.githubusercontent.com/8365816/128533253-766beb9c-9531-49bc-9bda-68da9ad8d9ab.png)
