### ISSUE TITLE
Condition Lab Active Effects are reset upon saving

### ISSUE THREAD

**Issue by sophiechiabatta** [death-save/combat-utility-belt#585]
**Describe the bug**
Condition Lab is clearing configured active effect attributes when they are submitted. When I hit "Submit Changes" the attributes are present. However, when I open "Active Effect Config" for that condition again, they have all been cleared. 

**To Reproduce**
1. Go to Condition Lab
2. Change "Mapping Type" to "System - Custom"
3. Click "Active Effect Config" for a condition
4. Configure active effect
5. Hit "Submit Changes"
6. Click "Active Effect Config" again for the same condition
7. All effects have been cleared

**Expected behavior**
Active effect configuration should save, rather than being cleared. 

**Screenshots**
https://imgur.com/a/2aoZWBQ

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.8
 - Game System / Version: dnd5e 1.4.1
 - CUB Version 1.6.1
 - Browser Foundry Application
 - OS Windows 10

**Additional context**
Foundry, game system, and CUB have all been updated. This bug persists when I disable all other modules. The attribute will eventually stick, after committing multiple times. I have not been able to determine a pattern in how many commits are required, nor in what precipitates a successful save.

**Comment by dutchvonrudder** [comment]
I have been able to reproduce this with the steps above.

**Comment by eclarke12** [comment]
When the Active Effect is submitted the entire Condition Mapping is saved to storage. This can be delayed or perhaps blocked and additionally the Condition Lab is now programmed to use the "in-memory" map instead of the one you just saved. So with these behaviours it leads to the issue you are experiencing.

As a workaround try submitting the Active Effect then close and reopen the Condition Lab completely.

**Comment by dutchvonrudder** [comment]
The suggested work around appears to work 100% of the time for me.

**Comment by eclarke12** [comment]
This does not appear to occur in the `Other/Imported` mapping based on my testing. I will determine why the `System - Custom` behaves this way.

**Comment by sophiechiabatta** [comment]
> 
> 
> When the Active Effect is submitted the entire Condition Mapping is saved to storage. This can be delayed or perhaps blocked and additionally the Condition Lab is now programmed to use the "in-memory" map instead of the one you just saved. So with these behaviours it leads to the issue you are experiencing.
> 
> **As a workaround try submitting the Active Effect then close and reopen the Condition Lab completely.**

Thank you for your quick and thorough response! I really appreciate it. 

This workaround works for me so long as I hit "Submit Changes" in the "Configure Active Effects" window but _do not_ hit "Save Mapping" within Condition Lab before closing it. 

Since it appears you're still troubleshooting based on your last comment I'll leave this bug report open, but feel free to close it whenever you like. I'm set.
