### ISSUE TITLE
Can not make attack rolls with Midi QOL getting error

### ISSUE THREAD

**Issue by Avitale34** [death-save/combat-utility-belt#590]
Getting this error when making an attack roll.

utils.js:850 Uncaught (in promise) TypeError: Cannot read property 'getCondition' of undefined
    at hasCondition (utils.js:850)
    at Workflow.checkAttackAdvantage (workflow.js:161)
    at Item5e.doItemRoll (itemhandling.js:379)
hasCondition    @    utils.js:850
checkAttackAdvantage    @    workflow.js:161
doItemRoll    @    itemhandling.js:379
Promise.then (async)
:gift:call_wrapper    @    libWrapper-wrapper.js:584
:gift:CONFIG.Item.documentClass.prototype.roll#0    @    libWrapper-wrapper.js:162
_onItemRoll    @    base.js:865
(anonymous)    @    base.js:591
dispatch    @    jquery.min.js:2
v.handle    @    jquery.min.js:2

**Comment by eclarke12** [comment]
Please comment/reopen if this is still happening in Foundry VTT v9 with CUB v1.8+
