### ISSUE TITLE
Bug removing concentration condition

### ISSUE THREAD

**Issue by Fridan99** [death-save/combat-utility-belt#591]
Describe the bug
****When casting a concentration spell, I get an error that prevents me from removing the concentration condition. 

**To Reproduce**
1. Cast a concentration spell
2. Then receive a red message
3. You cannot remove the concentration condition unless you refresh F5

I suspect a possible conflict with DAE or dnd5e system. Although I could not confirm it.

**Expected behavior**
Remove the concentration without problem

**Screenshots**
![2](https://user-images.githubusercontent.com/86131373/129616400-bedbf91e-57ef-49fa-a3e0-ef5434119cef.jpg)

**Environment Info (please complete the following information):**
 - Foundry Version: [0.8.8]
 - Game System / Version: [dnd5e 1.4.2]
 - CUB Version [1.6.1]
 - Browser [native Foundry app]
 - OS [Windows 10]

**Additional context**
https://www.reddit.com/r/FoundryVTT/comments/p3xdgj/cannot_remove_concentration_tag_while_using/

I am not the only one with the problem. See above

I don't use the midi concentration system, I ONLY use the CUB system. Previously everything worked correctly, and I have not modified or touched any options of any other module. I think I supose that the problem may have started when I updated the recent dnd5e system, because I don't remember updating the cub before the error.

A salute for the great module that you have.

**Comment by kjolern** [comment]
I tested this now and does not receive any errors when removing concentration.

Foundry version: [0.8.8]
Game System / Version : [dnd5e 1.4.2]
CUB Version [ 1.6.1]
Browser [ native foundry app]


OS [Windows 10]

I had a simmilar issue when the names did not match in the CUBPuter and condition lab though.

Screenshots : 

![image](https://user-images.githubusercontent.com/79190020/129978461-b19314c4-80d6-4f47-ac53-e8358eee074a.png)

**Comment by shodan89** [comment]
I have the smae bug with EVERY condition. If I apply and remove the condition, doing it a second time "removes" the condition and it's effects (in the sense that disadvantages are not applied anymore, for example) without removing the icons and the Effect on the list of active effects. It then becomes impossible to remove or apply the condition to that actor until reloading the application.
