### ISSUE TITLE
Editing hp on temp combatant causes icon to go crazy

### ISSUE THREAD

**Issue by ckdragons** [death-save/combat-utility-belt#598]
**Describe the bug**
After adding a temporary combatant to the Combat Tracker, changing the tokens hit points in the tracker (not on the token) makes the token lock up, thus locking up the CT, as it repeated edits the hp field adding zeros. The only way to stop this is to click End Combat multiple times or delete the token on the map.

**To Reproduce**
1. Add a temporary combatant.
2. Click on hp field in the Combat Tracker for the temporary combatant.
3. Change the # there. Doesn't matter if you type in "10" or "+2" or "-2"
4. Press Enter (or Tab) and the token starts repeatedly editing the field and adding a "0" to the end of the number, never ending.

**Expected behavior**
Editing the hp field in the Combat Tracker should have the same behavior has editing the hp field after right-clicking on the token.

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.9
 - Game System / Version: pf1e 0.79.0
 - CUB Version: 1.6.2
 - Browser: Firefox 91.0.2
 - OS: Windows 10 20H2

**Comment by ckdragons** [comment]
Further, I did try disabling all other modules in my testing to confirm this was not a conflict with another module.

**Comment by eclarke12** [comment]
Did some testing and discussed with the pf1e dev, using HP on temp combatants is a bit out of the scope of the gadget. If you want to do this, I would suggest dropping a race onto the temp combatant's sheet and then it should be ok to edit.
