### ISSUE TITLE
Duplicate concentration status

### ISSUE THREAD

**Issue by kuchrk24** [death-save/combat-utility-belt#599]
**Describe the bug**
Duplicate concentration status being applied. I can remove the one, but the other causes an error similar to what is described in [this issue](https://github.com/death-save/combat-utility-belt/issues/591) until I refresh the browser and then it is gone.

**To Reproduce**
1. Cast spell that required concentration
2. Chat shows two separate messages about concentration being applied. 
3. Removing the concentration status from the token menu works fine, the other shows in listed DAE effects, but trying to remove it throws an error.

**Expected behavior**
Concentration only applied once. Removing status throws no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/74018852/132617618-360c6b96-c1e8-422b-814a-1ac16c3a05c0.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.9
 - Game System / Version: DND 5e 1.4.3
 - CUB Version 1.6.2
 - Browser: Brave
 - OS Windows 10

**Comment by kuchrk24** [comment]
I just realized there is [another issue](https://github.com/death-save/combat-utility-belt/issues/595) that points to [460](https://github.com/death-save/combat-utility-belt/issues/460) that describes the same thing. Can probably close this one, but just echoing that this issue is occurring.

**Comment by Shuggaloaf** [comment]
> 
> 
> I just realized there is [another issue](https://github.com/death-save/combat-utility-belt/issues/595) that points to [460](https://github.com/death-save/combat-utility-belt/issues/460) that describes the same thing. Can probably close this one, but just echoing that this issue is occurring.

Hey Kuchrk24 I just closed that dup issue (I posted it) because the mod dev responded on the original issue #460. If you haven't yet, probably worth it to comment over there and just close this one out. Hopefully we'll get a resolution soon as having a 2nd screen running with another DM account would open up a lot of potential.
