### ISSUE TITLE
Add a way to change status ids in condition lab

### ISSUE THREAD

**Issue by BoltsJ** [death-save/combat-utility-belt#601]
**Is your feature request related to a problem? Please describe.**
When creating conditions, they are created with an id of `newcondition1` or `newcondition12` and this can't be changed.

**Describe the solution you'd like**
A way to change the id of a condition to something more meaningful

**Describe alternatives you've considered**
Exporting, text edititng and re-importing the condition mapping

**Additional context**

**Comment by eclarke12** [comment]
If the previous comment does not match your experience, please reopen with some more info/screenshots
