### ISSUE TITLE
CUBputer and Condition Lab buttons show up for players

### ISSUE THREAD

**Issue by ollster76** [death-save/combat-utility-belt#603]
I like to streamline the experience of my players, and prefer to have limited settings available to them. Currently both Condition Lab and Triggler are exposed to users.

I'd like a setting to hide all CUB settings from specific user groups.

I've entertained editing the Foundry CSS but this seemed a bit extreme...

**Comment by MorganVergara** [comment]
On mine, players can see CUBPuter and ConditionLab, but not Triggler. I'm on 1.6.2 of CUB and 0.8.9 of Foundry.

**Comment by ollster76** [comment]
Sorry, my mistake. Triggler is indeed hidden. The comment remains for CUBPuter and Condition Lab.

Thanks!
