### ISSUE TITLE
Simple Trigger does not show max as an option for property 2 (PF2e)

### ISSUE THREAD

**Issue by Kerdude** [death-save/combat-utility-belt#604]
The simple trigger does not show 'max' as a second property in PF2e system, making comparisons on hp.value impossible

![image](https://user-images.githubusercontent.com/77137657/134376376-f3f79be5-cd6e-4a31-a542-7fab29329476.png)

The following advanced trigger also does not work

![image](https://user-images.githubusercontent.com/77137657/134377861-d4481ad7-8b7f-40c8-99e9-3d5852d86b68.png)

**Comment by eclarke12** [comment]
This likely means the `max` value is not exposed by the system in the Actor template object (`game.system.template.Actor.templates`). Possibly because it's some kind of calculated attribute?
Your Advanced Trigger looks incorrect as I would assume the Token update path would be something like `actorData.attributes.hp.value` instead.

**Comment by Kerdude** [comment]
Strangely, I have it working in an old Foundry server. Here's a screenshot of the 'impossible' trigger (which I am afraid to mess with since I won't be able to recreate it since I can't pick max as property 2 any more lol)

![image](https://user-images.githubusercontent.com/77137657/134384195-bd27f00f-f681-41d8-9241-b816364dcca8.png)


And the relevant snip from settings.db

```{\"id\":\"6zv9pudu1g4go5l0\",\"triggerType\":\"simple\",\"category\":\"attributes\",\"attribute\":\"hp\",\"property1\":\"value\",\"operator\":\"lt\",\"value\":\"50%\",\"property2\":\"max\":\"\",\"pcOnly\":false,\"npcOnly\":false,\"notZero\":false,\"text\":\"attributes.hp.value < 50%\"},{\"id\":\"lqn59yjoc8kh3rok\",\"triggerType\":\"simple\",\"category\":\"attributes\",\"attribute\":\"hp\",\"property1\":\"value\",\"operator\":\"gt\",\"value\":\"50%\",\"property2\":\"max\":\"\",\"pcOnly\":false,\"npcOnly\":false,\"notZero\":false,\"text\":\"attributes.hp.value > 50%\"}]"}```

**Comment by eclarke12** [comment]
> Strangely, I have it working in an old Foundry server (same PF2e system version and same Foundry version as the non-working server). Here's a screenshot of the 'impossible' trigger (which I am afraid to mess with since I won't be able to recreate it since I can't pick max as property 2 any more lol)
> 
> ![image](https://user-images.githubusercontent.com/77137657/134384195-bd27f00f-f681-41d8-9241-b816364dcca8.png)
> 
> And the relevant snip from settings.db
> 
> `{\"id\":\"6zv9pudu1g4go5l0\",\"triggerType\":\"simple\",\"category\":\"attributes\",\"attribute\":\"hp\",\"property1\":\"value\",\"operator\":\"lt\",\"value\":\"50%\",\"property2\":\"max\":\"\",\"pcOnly\":false,\"npcOnly\":false,\"notZero\":false,\"text\":\"attributes.hp.value < 50%\"},{\"id\":\"lqn59yjoc8kh3rok\",\"triggerType\":\"simple\",\"category\":\"attributes\",\"attribute\":\"hp\",\"property1\":\"value\",\"operator\":\"gt\",\"value\":\"50%\",\"property2\":\"max\":\"\",\"pcOnly\":false,\"npcOnly\":false,\"notZero\":false,\"text\":\"attributes.hp.value > 50%\"}]"}`

Most likely when the old trigger was created, the `max` property was present in the actor schema that Triggler looks at. Perhaps it's been made into a calculated property or something along those lines since then.

**Comment by eclarke12** [comment]
Unfortunately I will be closing this issue for now. Because of the complexity of the pf2e system there's no easy workaround. I will be revising the Triggler gadget functionality later this year and at that time it should provide a better experience in these situations.
