### ISSUE TITLE
Concentration Check Prompts Don't Appear for Player Actors

### ISSUE THREAD

**Issue by BlackBadger777** [death-save/combat-utility-belt#618]
As long as only the GM is logged in, Concentrator seems to work fine. Whenever a token that has the "Concentrating" status takes damage, it sends the message to chat and also prompts the GM to roll the Concentration Check. On a failure, the status is automatically removed. 

However, as soon as other players join the game, this function doesn't work anymore for the player-controlled actors. The chat message "[Name] took damage and their concentration on is being tested (DC x)!" still appears when they take damage, but neither the GM nor the player get the prompt to actually roll the Concentration check. "Prompt Player" is checked in the CUBPuter. If the GM has an NPC with concentration, the prompt appears as it should. The issue seems to be with actors controlled by other players. 

I've tested this in a Test World without any other modules active. 

Foundry version: 0.8.9
DnD5e - Fifth Edition System: 1.5.3
CUB version: 1.7.0
Browser: Firefox, Chrome
OS: Windows 10

**Comment by eclarke12** [comment]
Confirmed. Fix coming in patch tomorrow-ish
