### ISSUE TITLE
Repository is missing package.json

### ISSUE THREAD

**Issue by wildj79** [death-save/combat-utility-belt#62]
This file is necessary for anyone that might want to fork this repository and contribute code. It holds all of the metadata needed for a node based project and without it, others won't be able to properly setup there development environment.

**Comment by eclarke12** [comment]
@wildj79 this is not a node based project. if it has any node files, that's a mistake.

**Comment by wildj79** [comment]
Right, but you're using node packages for development. Without the
package.json file in the repository, anyone who might try to contribute
can't, because they don't have the necessary development packages
installed, nor can they get them because there not defined in the
repository. The package.json file is a necessary file and should always be
committed into the source repo if it exits in a project.
