### ISSUE TITLE
"Enhanced Conditions does not work this game system" showing for dnd5e

### ISSUE THREAD

**Issue by stalker168** [death-save/combat-utility-belt#620]
CUB Enhanced Condition does not work on this game system. Please check the CUB Wiki for more information.
This is the message the module gives me when I try to interact with the Condition Lab. The problem appeared after updating the modules and restarting the CUB module.

When you click on the "Condition Lab" button, this notification appears instead of the window
![image](https://user-images.githubusercontent.com/31571343/141107468-605e5a96-b3f7-451f-ac43-86f06cd2c59c.png)

 - Foundry Version: 0.8.9
 - Game System / Version: dnd5e 1.5.3
 - CUB Version: 1.7.1
 - Browser: Chrome 95.0.4638.69
 - Game on server **The Forge**

When creating a new game with the same system version and CUB version, the Condition Lab button works correctly. The bug persists in the cloned version of the game. The message occurs even when only one CUB module is running.

**Comment by eclarke12** [comment]
@stalker168 we were talking on Discord?

**Comment by stalker168** [comment]
@eclarke12 no, we didn't speak on Discord.
Yes, and I won't be able to speak normally because I don't know English well.

**Comment by eclarke12** [comment]
> @eclarke12 no, we didn't speak on Discord. And I won't be able to speak normally because I don't know English well.

I meant "text" speak :) And don't worry you are doing fine!

I have seen reports of this issue since the update and will dive in over the next couple of days.

**Comment by stalker168** [comment]
@eclarke12 My discord nickname is Salamander#5299.
I can be found on the Foundry VTT server.

**Comment by eclarke12** [comment]
> @eclarke12 My discord nickname is Salamander#5299. I can be found on the Foundry VTT server.

Thanks! I don't think I need any more information at this time, but I will let you know.

**Comment by stalker168** [comment]
@eclarke12 I created a new world. Problems with Concentration saving throws. I guess this is due to the fact that I play in Russian. While I was switching languages ​​and switching concentrator  between MIDI and CUB, the same error occurred again.
I can't say exactly at what point it happened. But exactly somewhere in this range.

**Comment by CaosFR** [comment]
Hi I have the same issue since today. On a new world it's work to. I use the Concentration saving throws of CUB. If I turn off Concentration in MIDI en CUB, the problem persit.

I got this error when Enhanced Condition is on : 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
[Detected 2 packages: combat-utility-belt, lib-wrapper]
    at sidekick.js:293
    at Array.map (<anonymous>)
    at Function.generateUniqueSlugId (sidekick.js:293)
    at enhanced-conditions.js:781
    at Array.map (<anonymous>)
    at Function._prepareStatusEffects (enhanced-conditions.js:779)
    at Function._updateStatusEffects (enhanced-conditions.js:754)
    at Function._onReady (enhanced-conditions.js:87)
    at signal.js:94
    at Function._call (eval at <anonymous> (listeners.js:91), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at Game.setupGame (foundry.js:4403)
    at async Game._initializeGameView (foundry.js:5213)
    at async Game.initialize (foundry.js:4286)
```

And for Midi : 

```
TypeError: game.i18n is not a function
[Detected 2 packages: midi-qol, lib-wrapper]
    at midi-qol.js:185
    at Function._call (eval at <anonymous> (listeners.js:91), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at Game.setupGame (foundry.js:4403)
    at async Game._initializeGameView (foundry.js:5213)
    at async Game.initialize (foundry.js:4286)
```

**Comment by eclarke12** [comment]
@stalker168 / @CaosFR 
It looks like the issue was that Concentrator was creating a duplicate condition because it did not detect the existing one based on the name (language difference). I have fixed the bug in Enhanced Conditions that occurs when a condition name is duplicated. This will be fixed in the next update and it should just work when your world loads. You can then go into the Condition Lab and delete the duplicate Concentrating condition.

Also make sure you set the Concentrator `Concentrating Condition Name` setting to the correct name (eg. `Concentré` in French)

**Comment by CaosFR** [comment]
Thanks for you job :). Yes "Concentrating Condition Name" is set to "Concentré" ;)
