### ISSUE TITLE
Allow Multiple Turns

### ISSUE THREAD

**Issue by GhostwheelX** [death-save/combat-utility-belt#624]
Might it be possible to allow a creature to be added multiple times to the Initiative Tracker? I've done so by accident in the past, but it would be super helpful for some of the stranger enemies I throw at my party.

I realize that temporary combatants are a thing, but I'd like all the effects that automatically happen at the start and end of the creature's turn to go off, and it would be a huge help.

Thanks!

**Comment by eclarke12** [comment]
This is not something that I consider "in scope" for CUB sorry. If Temp Combatants don't fit the need I'd probably consider opening an issue on the official Foundry issue log, or the log for your system of choice. Sorry!
