### ISSUE TITLE
[v9 235] Unable to select tokens that have an active condition + condition icons not visible

### ISSUE THREAD

**Issue by CasanovaSekova** [death-save/combat-utility-belt#629]
**Describe the bug**
In v9, you cannot select a token with an active condition after a canvas refresh (scene change, refreshing page). You can pseudo-select it by creating a select box but you will not be able to move it, open the token context menu with it, etc. All you can do with a "pseudo-select" is to delete it. 

A minor bug is that the condition icons are no longer visible on tokens with an active condition.

**To Reproduce**
1. Add a condition to a token/actor
2. Change scenes or refresh the page
3. Try clicking on the token

**Expected behavior**
To be able to select and interact with tokens with an active condition after a canvas refresh + see condition icons on token

**Screenshots**

On clicking a token with a condition after a canvas refresh:
![image](https://user-images.githubusercontent.com/95392008/145741749-ea39bdb4-7f16-4859-be10-8ff06bfb0402.png)

Confirmation that CUB is the only active module:
![image](https://user-images.githubusercontent.com/95392008/145741757-b11e8457-36d1-4ccb-a8e9-dd88cd7d099c.png)

**Environment Info (please complete the following information):**
 - Foundry Version: v9 Test Build 235
 - Game System / Version: dnd5e 1.5.5
 - CUB Version [e.g. 1.3.0]: 1.7.3
 - Browser [e.g. chrome, safari]: Vivaldi
 - OS [e.g. Windows 10]: Windows 11

**Additional context**
Posted in discord w/ Errational's awareness but posted here too for his convenience

**Comment by tjlanza** [comment]
I can confirm this same issue in a slightly different environment:

- Foundry Version: v9 Testing 2, Build 235
- Game System / Version: Shadowrun 5E 0.7.23
- CUB Version: 1.7.3
- Browser: Chrome 96.0.4664.93
- OS: Windows 10 client, Ubuntu 20.04.3 LTS server

**Comment by Rehvaro** [comment]
If this is useful, I can confirm this problem with:

Foundry V9 Stable - Build 238 (launched as server with NodeJS)
Game system DnD 5E v1.5.6
CUB v1.7.3
Firefox 95.0.2
OS Server Side: Fedora 34
OS Client Side: Windows 11

**Comment by eclarke12** [comment]
fixed in next release
