### ISSUE TITLE
[v9 235] Cannot browse CUBputer

### ISSUE THREAD

**Issue by CasanovaSekova** [death-save/combat-utility-belt#630]
**Describe the bug**
The CUBputer terminal does not allow you to browse the menus (go between pages in the CUBputer) in v9. Pre-existing settings seem to be working but the settings in the terminal are currently inaccessible. 

With the CRT style mode on, the terminal window moves to the right of the right-hand Foundry navigation menu and spans the area vertically and fills in a large horizontal space. 

**To Reproduce**
1. Go to settings
2. Click on CUBputer
3. Click on Select Gadgets
4. Press any of the gadgets

**Expected behavior**
To open the CUBputer settings for specific add-ons. 

**Screenshots**
On clicking CUBputer settings:
![image](https://user-images.githubusercontent.com/95392008/145742595-b06b7153-8e97-48ce-bc3a-53805f62158e.png)

Screenshot of the CRT issue:
![image](https://user-images.githubusercontent.com/95392008/145742631-398d3610-218c-4b93-91ab-d77968023583.png)

**Environment Info (please complete the following information):**
- Foundry Version: v9 Test Build 235
- Game System / Version: dnd5e 1.5.5
- CUB Version [e.g. 1.3.0]: 1.7.3
- Browser [e.g. chrome, safari]: Vivaldi
- OS [e.g. Windows 10]: Windows 11

**Additional context**

**Comment by eclarke12** [comment]
fixed in next release
