### ISSUE TITLE
Auto-sorting rows in Condition Lab

### ISSUE THREAD

**Issue by weepingminotaur** [death-save/combat-utility-belt#632]
It's pretty tedious to have to manually sort every condition just so they appear properly in the Token HUD or Token Action Hud. Condition rows should automatically sort alphabetically in the Condition Lab.

**Comment by megahead11** [comment]
I think this should be optional, like with a sort button. Some of us have conditions sorted by groups.

**Comment by weepingminotaur** [comment]
Fair enough. The option to sort automatically works for me.
