### ISSUE TITLE
"Tokens determine NPC name visibility" doesnt hide name on hover in tracker

### ISSUE THREAD

**Issue by DieterKosken** [death-save/combat-utility-belt#634]
**Describe the bug**
Checking this under system settings hides the visible name. However, when you mouse over the token image in tracker it pops up with the name. 

**To Reproduce**
Check the setting
Start encounter with NPC
hover mouse cursor over token image in tracker

**Expected behavior**
No name should be displayed or something generic such as creature would be fine as well. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41964137/147019479-8c6439cb-058d-4dcf-9090-ef34c05c78b1.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.9
 - Game System / Version: 2.20.2
 - Browser chrome
 - OS [e.g. Windows 10]

**Comment by eclarke12** [comment]
What game system is this?

**Comment by DieterKosken** [comment]
Im sorry there must have been some github login thing with my browser. After logging in it took me to the wrong repo.
