### ISSUE TITLE
Hide Names not working in PF1 in V9.236

### ISSUE THREAD

**Issue by happydevil37** [death-save/combat-utility-belt#639]
Hi, the hide names feature doesnt appear to be working at all in PF1 (not sure if it should though).
Doesn't throw any error messages, just does nothing and no icon appears in the token name like it does in PF2
![CUB_setup](https://user-images.githubusercontent.com/28553250/147422218-ff36c09e-35c8-45ef-a4ce-2d93cca918b7.png)
.

**Comment by eclarke12** [comment]
When you say not working at all, which places is the name not being hidden? (eg. chat log, combat tracker etc)

**Comment by happydevil37** [comment]
unless I am wrong, shouldn't there be a little mask icon on the actor sheet ? this doesnt appear for me on PF1 (it does on PF2).  and when you hover over the actor, the portrait popup displays the name of the creature even tho CUB says hide... Unless I am doing something wrong.
The names also appear in the combat tracker and are not masked either.

**Comment by eclarke12** [comment]
I just tested with Foundry v9 238, CUB v1.8.0 and PF1e 0.80.3 and it appears to be working for me

Player view:
![image](https://user-images.githubusercontent.com/42503461/148496859-ccb7793a-0c7f-4b9b-a7e1-2bfc3f751960.png)

GM view:
![image](https://user-images.githubusercontent.com/42503461/148496907-75965087-3474-44db-b5ab-f3919f3108af.png)
![image](https://user-images.githubusercontent.com/42503461/148496938-625222b2-c71b-42f4-a8cf-f9e51a625e53.png)

**Comment by happydevil37** [comment]
definitely doesn't work for me ... Pathfinder 0.80.3, CUB 1.8.0 and Foundry v9.241 (upgraded this morning.  

There was an update the the PF1 system a few days ago, and its working by using the hide names flag in the settings on the actor sheet

I still don't get the little mask thing - I have a work around for now.

Thanks

**Comment by eclarke12** [comment]
> definitely doesn't work for me ... Pathfinder 0.80.3, CUB 1.8.0 and Foundry v9.241 (upgraded this morning.
> 
> There was an update the the PF1 system a few days ago, and its working by using the hide names flag in the settings on the actor sheet
> 
> I still don't get the little mask thing - I have a work around for now.
> 
> Thanks

Do you mind sharing your system settings?

Also if you have time, clone your world, then in the clone disable all modules except CUB and try again. Thanks!

**Comment by awsomedonkey** [comment]
I also have this issue in combat tracker using CUB 1.8.1, WFRP 5.0.5

**Comment by eclarke12** [comment]
> I also have this issue in combat tracker using CUB 1.8.1, WFRP 5.0.5

It appears to be working for me. 
![image](https://user-images.githubusercontent.com/42503461/152100576-684718f2-8070-42f8-ac00-916741243abe.png)

Please open a new issue and include some more details/screenshot thanks!

**Comment by eclarke12** [comment]
@happydevil37 this continues to work for me with just PF1e and CUB enabled. I suspect another module is causing an issue. Closing for now.
