### ISSUE TITLE
[ENH] Attribute Tracking and editing

### ISSUE THREAD

**Issue by erogroth** [death-save/combat-utility-belt#64]
Would love to see the ability to track and edit HP from the combat tracker. Additionally the ability to see attributes like AC and Speed. Basically anything that you may need to know quickly about a combatant in combat. 

Finally if there was a way to add conditions from the combat tracker and have the condition token visible in the tracker that would be a bonus! Thanks

**Comment by eclarke12** [comment]
This will be handled in https://github.com/death-save/combat-carousel-public
