### ISSUE TITLE
V9, issue with custom conditions from Condition Lab not showing as condition icons. 

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#643]
In PF2 3.1.3 on V9, one functionality that I used to rely on no longer seems to work. I used to define custom conditions in the Condition Lab and then use macros to set/unset the conditions. In V9, this causes the condition to output to chat but not set the condition and not show the condition name. However it remembers that the condition is properly set or unset.

The macro I use is very simple 

if (game.cub.hasCondition("Ready Weapon")) {
	game.cub.removeCondition("Ready Weapon");
	} else {
	game.cub.addCondition("Ready Weapon");
	}

The condition used by that macro:

![image](https://user-images.githubusercontent.com/4083812/147892609-5083d5d9-e05c-4ac8-af59-1e5ed0d9d351.png)

**Comment by eclarke12** [comment]
PF2e is not currently supported by Enhanced Conditions due to the customisation of the effects framework implemented by the system.
