### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [death-save/combat-utility-belt#648]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by eclarke12** [comment]
? Compatible core version is set to `9.238`
https://github.com/death-save/combat-utility-belt/blob/0253be3d7a8201fcffa1c6d061d7a5a42d802d04/module.json#L17

**Comment by brunocalado** [comment]
> ? Compatible core version is set to `9.238`
> 
> https://github.com/death-save/combat-utility-belt/blob/0253be3d7a8201fcffa1c6d061d7a5a42d802d04/module.json#L17

Yes, but if leave like that every new v9 build will result in compatibility warning. 

Just set to  "compatibleCoreVersion": "9" which mean this module will work for v9

**Comment by eclarke12** [comment]
> Yes, but if leave like that every new v9 build will result in compatibility warning.
> 
> Just set to "compatibleCoreVersion": "9" which mean this module will work for v9

I think you misunderstand. Defining compatibility for an entire version generation is best left to content modules and more static content. Complex modules like CUB should not be flagged as compatible with an entire generation as I can't ensure each subsequent patch is going to work. When I validate that CUB works with a Foundry version I update the manifest.

Note this mentality is described in the Foundry issue you linked:
> This module is extra cautious and explicitly defines everything
{
  "minimumCoreVersion": "9.1700", // Specific build
  "compatibleCoreVersion": "9.1719" // Specific build
}
