### ISSUE TITLE
Overlay icons hog the z-index, hiding other tokens

### ISSUE THREAD

**Issue by geoidesic** [death-save/combat-utility-belt#652]
If you have a token with Condition Lab conditional icon applied, and you then move another token onto that, the overlay overlays both tokens, which means your second token is hidden behind the overlay. This causes a lot of confusion with the Dead or Unconscious overlay, whereby characters can't see an live opponent because they think it's dead.

Even if your token has a status, like a Midi-SRD haste spell e.g., that will be hidden by the death status of any token behind it.

**Comment by eclarke12** [comment]
Does this issue occur when CUB is disabled?

**Comment by geoidesic** [comment]
Yes. It persists, so I guess this is not CUB to blame. What do you think is to blame? The 5e system?

**Comment by eclarke12** [comment]
> Yes. It persists, so I guess this is not CUB to blame. What do you think is to blame? The 5e system?
> […](#)
> Sent from my iPhone
> On 18 Jan 2022, at 07:25, errational ***@***.***> wrote: ﻿ Does this issue occur when CUB is disabled? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

Sounds like a native foundry issue. You could try installing another system and see if it happens there too.
