### ISSUE TITLE
Foundry Server Debug Log shows warning...

### ISSUE THREAD

**Issue by karpana** [death-save/combat-utility-belt#659]
When I restart my Foundry instance, this message is continually present in the `debug.log` file.

Foundry Version: v9 build 249
System: PF1
Host/Server Operating System: Raspberry Pi 4.
CUB Version: 1.8.1

```
{"level":"warn","message":"Package combat-utility-belt contains 2 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2022-02-07 09:18:04"}
```

**Comment by eclarke12** [comment]
What version of CUB are you using?

**Comment by karpana** [comment]
Sorry ... I should have included that in my initial post.
CUB Version: 1.8.1

(I"ve also updated this back into the intial report above)

**Comment by eclarke12** [comment]
> Sorry ... I should have included that in my initial post. CUB Version: 1.8.1
> 
> (I"ve also updated this back into the intial report above)

Weird. I cannot see any references to `entity`  in the compendium DBs when I checked my local copy.

**Comment by karpana** [comment]
Is it possible it's the references at lines 78 and 86 of the module.json file?

I used textpad to search/scan for the word entity in the entire "installed" copy of my foundry setup, and provided the results below.

It's the only file (outside of LICENCE) that has 2 references?

![image](https://user-images.githubusercontent.com/15716173/153066868-afd81cac-a78a-470a-8881-939f481febc8.png)

Don't get me wrong, this isn't a breaking change, but it raises a future compatibility issue in future versions.


Full Search Summary of `entity` (counts by file)

```
Searching for: entity
\\foundry\modules\combat-utility-belt\API.md: 31
\\foundry\modules\combat-utility-belt\CHANGELOG.md: 5
\\foundry\modules\combat-utility-belt\LICENSE: 2
\\foundry\modules\combat-utility-belt\module.json: 2
\\foundry\modules\combat-utility-belt\lang\en.json: 7
\\foundry\modules\combat-utility-belt\lang\ja.json: 5
\\foundry\modules\combat-utility-belt\lang\ko.json: 5
\\foundry\modules\combat-utility-belt\modules\concentrator.js: 81
\\foundry\modules\combat-utility-belt\modules\mighty-summoner.js: 1
\\foundry\modules\combat-utility-belt\modules\pan-select.js: 4
\\foundry\modules\combat-utility-belt\modules\signal.js: 1
\\foundry\modules\combat-utility-belt\modules\enhanced-conditions\condition-lab.js: 8
\\foundry\modules\combat-utility-belt\modules\enhanced-conditions\enhanced-conditions.js: 77
\\foundry\modules\combat-utility-belt\modules\triggler\triggler.js: 29
Found 258 occurrence(s) in 14 file(s), 503 ms
```

**Comment by eclarke12** [comment]
That's it. Not sure how I missed those in the manifest
