### ISSUE TITLE
Adding Rows to the Condition Lab duplicates Ids

### ISSUE THREAD

**Issue by icantbelieveitsnotwalrus** [death-save/combat-utility-belt#661]
**Environment Info**
Foundry v9.249
CUB v1.8.2
Game System: DnD5e v1.5.7
Browser: Chrome
OS: Foundry hosted in Ubuntu 1804; User connecting through Windows 10
Gadget: Enhanced Conditions

**Describe the bug**
When adding conditions past the 24th condition, all subsequent conditions seem to get treated as if they are the 25th condition. When activating any of these conditions, all of the conditions 25 and up are highlighted simultaneously and the 25th condition is what gets applied to the token. Additionally, in the Condition Lab, clicking the Configure Active Effect button for any of these conditions opens the Configure Active Effect window for the 25th condition.

**To Reproduce**
1. Set "Remove Default Status Effects" to true in the CUBPuter
2. In the Condition Lab, use the System - Custom mappings.
3. Add additional rows of conditions until you have 26+ total conditions.
4. Save the mapping.
5. Attempt to use any of the conditions on a token from the last row in the condition pop-up.

**Screenshots**
Clicking the 27th condition (Haste):
https://i.imgur.com/KcTAvHc.png

Applies condition 25 (Bless) and highlights all conditions 25 and beyond.
https://i.imgur.com/Ev2G6tX.png

In the Condition Lab, clicking the Active Effect Config button for the 26th condition (Flying):
https://i.imgur.com/9Y1UgE6.png

Opens the Active Effect Config window for condition 25 (Bless):
https://i.imgur.com/wEt3woO.png

**Comment by eclarke12** [comment]
@icantbelieveitsnotwalrus can you please attach an export of your condition lab?

**Comment by icantbelieveitsnotwalrus** [comment]
Sure thing! Looks like they're using the same ID values, which makes sense... I tried deleting the ones with ID of "new-condition-1" and "new-condition-11" and re-adding them, but they seemed to continue getting saved with the those same IDs when re-adding. 

However, by manually changing the JSON file to use unique IDs, setting their "isChanged" flags to false and re-importing it, it seems to have fixed everything and I can now add new conditions that work without issue. Not really sure what caused the issue to begin happening in the first place, though.

[cub-dnd5e-condition-map.txt](https://github.com/death-save/combat-utility-belt/files/8056527/cub-dnd5e-condition-map.txt)

**Comment by eclarke12** [comment]
> Sure thing! Looks like they're using the same ID values, which makes sense... I tried deleting the ones with ID of "new-condition-1" and "new-condition-11" and re-adding them, but they seemed to continue getting saved with the those same IDs when re-adding.
> 
> However, by manually changing the JSON file to use unique IDs, setting their "isChanged" flags to false and re-importing it, the conditions work, so that works for me as a work-around. However, if I add more conditions through condition lab after that, the first one that gets added again has the ID of "new-condition-1" and any ones after that all have the ID of "new-condition-11", so the ones that all get the ID of "new-condition-11" are problematic unless I modify and re-import the JSON file again.
> 
> [cub-dnd5e-condition-map.txt](https://github.com/death-save/combat-utility-belt/files/8056527/cub-dnd5e-condition-map.txt)

Reimporting the broken map should also have fixed it but I'm concerned the fix in CUB 1.8.1 didn't resolve it when you created the conditions.

**Comment by Reivin800** [comment]
I´m having the same problem
I tried to Manually change the "isChanged" flags to false
Bu it did not fix the problem 


[cub-dnd5e-condition-map.txt](https://github.com/death-save/combat-utility-belt/files/8057228/cub-dnd5e-condition-map.txt)

**Comment by eclarke12** [comment]
Validated in testing. Will be fixed next release.

**Comment by icantbelieveitsnotwalrus** [comment]
Working great! Thanks!

**Comment by Reivin800** [comment]
Fixed for me too.
Thank you very much!!!
