### ISSUE TITLE
Different die for Initiative

### ISSUE THREAD

**Issue by Orionox** [death-save/combat-utility-belt#668]
**Is your feature request related to a problem? Please describe.**
No specific problem that I'm trying to solve other than the extreme randomness of rerolling initiative each turn.

**Describe the solution you'd like**
I want to be able to change what dice are rolled for initiative. I would like to be able to make initiative 5d4 or 3d6 or 3d8 or 2d10. Each of these reduces the randomness of the initiative roll without making the initiative completely static.

**Describe alternatives you've considered**
It would also be cool if we got this option for skill checks as well as an option.

**Additional context**
using 1d20 to re-roll initiative each turn introduces randomness in turn order, and that is a good thing in my opinion, but it introduces a little too much. This leads to bad feeling situations like casting an "until my next turn ability" and then going immediately afterward wasting the ability or spell slot. To curb this randomness I would like to have the ability to change the die that is rolled to determine initiative. This would allow me to use a combination of dice that have a rounder bell curve making it so that there is SOME randomness in the initiative count without it being wildly swingy.

**Comment by eclarke12** [comment]
This is a nice idea, but out of scope for what CUB is doing with reroll initiative I'm afraid.
