### ISSUE TITLE
Condition Lab FX automatically removed in 3.5

### ISSUE THREAD

**Issue by Gulmyros** [death-save/combat-utility-belt#669]
**Describe the bug**
Condition Lab token effects are correctly applied, but then immediately removed, when used in the 3.5e ruleset.

**To Reproduce**
1. Load world with 3.5e ruleset.
2. Install Combat Utility Belt
3. Activate Enhanced Conditions, reset Condition Map to default status.
4. Open Triggler, create simple trigger: attributes.hp.value < 0
5. In Condition Lab, choose any condition and use trigger as "Apply Trigger"
6. Leave "Remove Trigger" unset.
7. Update token hp to less than zero (direct edit, apply combat result, via macro, or other method).
8. Effect is instantly added, condition icon is displayed, then immediately removed, and the condition is removed. Token hp value does not change further.

**Expected behavior**
Effect should be added, effect icon should be added, and effect should remain unless deleted manually or via another trigger condition.

**Environment Info (please complete the following information):**
Using Windows 11 64bit
Foundry is 9.255 (local app, not in separate browser)
3.5e SRD is 0.99.5
CUB is 1.8.4

**Additional context**
If the Condition Lab and Triggler are incompatible with 3.5 because of XYZ, would love to know what XYZ is so I can bring it to the 3.5 developer's attention.

**Screenshots**
![CUB-error](https://user-images.githubusercontent.com/95724201/157993723-9eb8345d-43c6-492e-a05b-5927e73548c9.png)
![CUB_error](https://user-images.githubusercontent.com/95724201/157993755-ac24bcd5-587d-48cf-95fe-322bc4df4ba6.gif)

**Comment by eclarke12** [comment]
I was able to implement a workaround for this issue, however it may have unintended consequences. The fix will be in CUB v1.9.0

Basically the 3.5e system actively removes effect icons that aren't applied by a condition/buff from within the system, or manually added via the token HUD.
