### ISSUE TITLE
game.cub applies to selected token, not the token that triggered the macro (Triggler)

### ISSUE THREAD

**Issue by TogaParty** [death-save/combat-utility-belt#671]
**Describe the bug**
When a macro executes that is triggered from Triggler (or, I expect, any source) using game.cub, the macro executes against the selected token instead of the one that triggered the macro.  e.g.

Macro triggered by Triggler (attributes.hp.value > 75% attributes hp max:

if (!game.cub.hasCondition("Not Injured (>75%)")) {
        await game.cub.addCondition("Not Injured (>75%)");
}

The macro executes on the selected token, not the one that has HP reduced at or below 75%.

**To Reproduce**
Macro triggered by Triggler (attributes.hp.value > 75% attributes hp max:

if (!game.cub.hasCondition("Not Injured (>75%)")) {
        await game.cub.addCondition("Not Injured (>75%)");
}

The macro executes on the selected token, not the one that has HP reduced at or below 75%.

**Expected behavior**
Should execute against the token that triggered it, or an alternate method is needed to specify the token to affect.  I do not see a way to leverage game.cub.addCondition or game.cub.removeCondition against tokens other than the selected one.

**Screenshots**

**Environment Info (please complete the following information):**
 - Latest (9x)
 - SW5e
 - Latest
 - Chrome
 - Win10

**Additional context**

**Comment by eclarke12** [comment]
You need to pass in the 2nd parameter to those methods or CUB will start looking for a token itself (starting with those you have controlled). https://github.com/death-save/combat-utility-belt/blob/master/API.md#EnhancedConditions.addCondition

**Comment by eclarke12** [comment]
To be clear for future reference: in a Triggler triggered macro, CUB will pass the `token` or `actor` that triggered the Triggler trigger. So you can reference those via the inherent `token` or `actor` variables within the macro.
