### ISSUE TITLE
Condition that adds item/ability to inventory

### ISSUE THREAD

**Issue by lucaspicerni** [death-save/combat-utility-belt#673]
In some systems, the condition is an item that is added to the character's inventory upon application of the condition. It could be implemented via drag and drop in the conditions lab, below the reference entry, to specify which item/feature to add to the inventory.

**Comment by eclarke12** [comment]
Thanks for the suggestion! Do you have an example of a system that handles conditions this way?

**Comment by lucaspicerni** [comment]
Sure! In [Chronicles of Darkness 2e](https://gitlab.com/MarlQ/mta), there are two types of "status": Tilts (temporary and often combat-related) and Conditions (usually long-term or sometimes permanent). Conditions have longer descriptions and are related to how the character earns XP. There is an item template just for Conditions and also a special space for them on the character sheet:
![image](https://user-images.githubusercontent.com/95550238/164050119-4059dea8-8b37-4a41-adec-f22017ad184f.png)
![image](https://user-images.githubusercontent.com/95550238/164050355-98780926-1662-4267-b24b-35f4bf047fc6.png)

Even on systems that don't use conditions in this way, I can imagine uses for this function: in D&D itself, I limit the visibility of the active effects tab for my players (not very friendly settings for boomers like me and my friends hahaha) , so it would be interesting to be able to add a passive feature, merely informative, so that they could read the description of the effects that affect them without having to look for the reference that the CUB sent to the chat, in situations where many rolls have already passed. Something like that:
![image](https://user-images.githubusercontent.com/95550238/164049072-2c9bd118-82bf-4d0e-94a2-a1e4732de9f4.png)

Thanks for the willingness!

**Comment by eclarke12** [comment]
This is not going to make it into CUB... HOWEVER with the ability to trigger macros from Conditions you should be able to get the functionality you desire.

Something like:
```js
const item = game.items.getName("Scary Condition Item");
actor.createEmbeddedDocuments("Item", item);
ui.notifications.info(`${item.name} added to ${actor.name}`);
```

I am closing this issue but feel free to comment if you have questions.

**Comment by lucaspicerni** [comment]
Just to confirm: does this macro example you used *create* the item in inventory? Or import it?

**Comment by eclarke12** [comment]
> Just to confirm: does this macro example you used _create_ the item in inventory? Or import it?

This would add an existing "world" item into an Actor's inventory. If the item resides in a Compendium there's some additional steps required. I would suggest jumping into the `macro-polo` channel of the official [Foundry Discord](https://discord.gg/foundryvtt) if you need assistance.

**Comment by lucaspicerni** [comment]
Thank you for your assistance.
