### ISSUE TITLE
Sorting Condition Lab causes Condition Effects to be lost on save if Condition changes position

### ISSUE THREAD

**Issue by strongpauly** [death-save/combat-utility-belt#676]
**Describe the bug**
Saving conditions removes all Effects from the Active Effects of those conditions

**To Reproduce**

1. Start with no values in Other/Imported mapping in Condition Lab
2. Decompress and Import [effects.json.zip](https://github.com/death-save/combat-utility-belt/files/8734358/effects.json.zip) into the Condtion Lab
3. Save to Enable Active Effects button
4. Open Active Effects button for Faerie fire, for example, and click on Effects to see several effects to be applied.
5. Close the dialog.
6. Save again.
7. Repeat step 4 to see that those effects are no longer present.

**Expected behavior**
Should not lose effects between saves.  

Note sometimes does save correctly, but sorting the effects will always get them to disappear.

**Screenshots**
<img width="578" alt="Screenshot 2022-05-19 at 22 47 01" src="https://user-images.githubusercontent.com/853954/169410106-fa953385-b09f-4138-b17d-90596d1ca509.png">
<img width="570" alt="Screenshot 2022-05-19 at 22 49 21" src="https://user-images.githubusercontent.com/853954/169410401-12546091-2ca5-41d1-a8d9-8cf76c5b9de1.png">

**Environment Info:**
 - Foundry Version: Version 9, 9.269
 - Game System / Version: dnd5e
 - CUB Version: 1.9.0
 - Electron Client
 - OS: Mac OSX

**Comment by eclarke12** [comment]
Sorry for the inconvenience and thanks for the in-depth report, I don't remember experiencing this while testing the new version so I will take a look.

**Comment by eclarke12** [comment]
I was able to reproduce this when I sort the lab.
