### ISSUE TITLE
Imported Map removed if you change mapping type. 

### ISSUE THREAD

**Issue by Orionox** [death-save/combat-utility-belt#677]
**Describe the bug**
If you import a condition map, but then toggle the mapping type to inferred or custom, the imported map is lost even if you saved it.  I'm unsure if this is a bug or intended, but if its intended it really sucks to lose an imported map that you've edited when you thought it was saved just cause you wanted to check something about default conditions. 

**To Reproduce**
1. import map type
2. put the drop down to custom or infered
3. put the drop-down back to "imported."

**Environment Info (please complete the following information):**
 - Foundry Version: 9v
 - Game System / Version: Lancers 1.2.0
 - CUB Version: 1.90
 - OS [Windows 10]

**Comment by eclarke12** [comment]
This is not intended behaviour as far as I remember--maps of each type should be saved until overridden.
