### ISSUE TITLE
TidySheet5e shows error notification if Exhaustion mapping in Tidysheet does not match CUB

### ISSUE THREAD

**Issue by gris-x** [death-save/combat-utility-belt#683]
**Describe the bug**
When updating temp HP on my character, I get a bunch of error messages

**To Reproduce**
1. Go to character token
2. Open char sheet
3. Update temporary hp

**Expected behavior**
No error message showing up

**Screenshots**

![image](https://user-images.githubusercontent.com/73260133/173164337-d01c4a75-ba4b-4ed1-ae1c-206a4616cc20.png)

**Environment Info (please complete the following information):**
 - Foundry Version: latest
 - Game System / Version: dnd5e
 - CUB Version 
 - Browser Chrome
 - OS  Windows 10

**Additional context**
from F12

5 
enhanced-conditions.js:1414 Combat Utility Belt - Enhanced Conditions | ENHANCED_CONDITIONS.RemoveCondition.Failed.NoMapping

**Comment by gris-x** [comment]
CUB v 1.9.1

**Comment by CaosFR** [comment]
Same error when I modify anything in a character sheet of my player.

**Comment by CaosFR** [comment]
Same error and environnement when I modify anything in a character sheet of my players (PJ). Zero problem on monster character sheet (NPC).
If I disable combat-utility-belt it's ok. If I just disable Condition Lab the problem persist.

**Update : If I disable "Tidy5e Sheet" module, the problem look be solve. Are they any incompatibility ?** 

Console
enhanced-conditions.js:1414 Combat Utility Belt - Enhanced Conditions | ENHANCED_CONDITIONS.RemoveCondition.Failed.NoMapping

**Comment by gris-x** [comment]
it seems to be linked to the custom exhaustion condition in Tidy sheet setup under GM Options. setting no exhaustion automation seems to fix it.

**Comment by eclarke12** [comment]
Most likely this is related to translation issues.

**Comment by CaosFR** [comment]
> Most likely this is related to translation issues.

It's seen to be, I'm french. My previous CUB bug was a translation issues.

**Comment by CaosFR** [comment]
@eclarke12 Thanks for your help. Yes my condition Lab is in French. 

I have follow your advise and find the hardcoded name of Exhaustion in TidySheet.
In French its "Fatigue 1" to "Fatigue 6". I have modify condition Lab to match with it and the NoMapping error message it's solve.

I have a new error in the console log when I modify Exhaustion in the PC (the error is only for exhaustion), see below : 

Uncaught (in promise) 
TypeError: Cannot read properties of null (reading 'drawShape')
[Detected 1 package: combat-utility-belt]
    at SmoothGraphics.drawShape (SmoothGraphics.ts:526:1)
    at SmoothGraphics.drawRoundedRect (SmoothGraphics.ts:475:1)
    at Token5e._drawEffect (token.js:149:12)
    at async Promise.all (index 0)
    at async Token5e.drawEffects (foundry.js:38383:7)
  | drawShape | @ | SmoothGraphics.ts:526
-- | -- | -- | --
  | drawRoundedRect | @ | SmoothGraphics.ts:475
  | _drawEffect | @ | token.js:149
  | await in _drawEffect (async) |   |  
  | _onEmbeddedDocumentChange | @ | foundry.js:13827
  | _onCreateEmbeddedDocuments | @ | foundry.js:13792
  | _handleCreateEmbeddedDocuments | @ | foundry.js:10078
  | _createEmbeddedDocuments | @ | foundry.js:9967
  | await in _createEmbeddedDocuments (async) |   |  
  | create | @ | backend.mjs:95
  | await in create (async) |   |  
  | createDocuments | @ | document.mjs:338
  | createEmbeddedDocuments | @ | document.mjs:522
  | addCondition | @ | enhanced-conditions.js:1230
  | updateExhaustion | @ | exhaustion.js:174
  | (anonymous) | @ | exhaustion.js:186
  | _call | @ | foundry.js:294
  | callAll | @ | foundry.js:253
  | callback | @ | foundry.js:10313
  | (anonymous) | @ | foundry.js:10251
  | _handleUpdateDocuments | @ | foundry.js:10251
  | _updateDocuments | @ | foundry.js:10131
  | await in _updateDocuments (async) |   |  
  | update | @ | backend.mjs:154
  | await in update (async) |   |  
  | updateDocuments | @ | document.mjs:373
  | update | @ | document.mjs:456
  | (anonymous) | @ | tidy5e-sheet.js:129
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

**Comment by eclarke12** [comment]
@CaosFR I'm not sure about that last error. Can you confirm you've configured your CUB and TidySheet as follows (replacing Exhaustion with Fatigue):
![image](https://user-images.githubusercontent.com/42503461/174230424-8bac92da-5869-42bd-8c58-50d63e1bfe4d.png)

**Comment by CaosFR** [comment]
@eclarke12 Yes, I confirm. I had configured like you say, see below 
![Capture](https://user-images.githubusercontent.com/37581932/174332559-5f7c6b49-7b2e-467d-ac2e-9a19925b1fde.PNG)

I have make some search, the problem come from Automated Animations module (https://github.com/otigon/automated-jb2a-animations). Why ? I realy dont know, I try to find. Does have I to open a new topic for this error (Is not link to Tidy) ?
