### ISSUE TITLE
Filtering & Active Effect Changes results in blank conditions.

### ISSUE THREAD

**Issue by KajinStyle** [death-save/combat-utility-belt#687]
While using the filter, I made changes to the Active Effects and click save, then save on the mapping changes button since it lite up blue for some reason. Immediately after, every condition but the one in the filter search was blank.

![CUB1](https://user-images.githubusercontent.com/45796595/174499053-1748d3e9-e5a3-4013-8997-8d45295f9665.png)
![CUB2](https://user-images.githubusercontent.com/45796595/174499056-03963435-b529-4cf0-b012-5776ccf2e3a5.png)
![CUB3](https://user-images.githubusercontent.com/45796595/174499059-11abbd82-e37b-43bb-92cc-3ceb2c58d4c0.png)

**Environment Info (please complete the following information):**
 - Foundry Version: [V9 - Build 269]
 - Game System / Version: [DnD 1.6.1]
 - CUB Version [1.91]
 - OS [Windows 11 Pro]

**Additional context**
I do have a ton of mods installed. I doubt most will interfere but maybe Monk's Little Details is the closest. I won't bother disabling/enabling 50+ mods just to test this. This bug is pretty straightforward. If no one can reproduce then I'll investigate further but I have DnD prep to do and doing an deeper investigation will eating up what little free time I have.

**Comment by eclarke12** [comment]
Sorry for the inconvenience. If you close your Condition Lab without saving, it should be restored. I will investigate the issue further.
