### ISSUE TITLE
EnhancedConditions#applyCondition API method no longer works

### ISSUE THREAD

**Issue by Vrelvel** [death-save/combat-utility-belt#689]
**Describe the bug**
Followed instructions of tutorial on Foundry.com for enhanced conditions. no conditions set on targets as expected. Functionality broken.

**To Reproduce**
See above. Expected result in tutorial not achievable. Settings are identical to those in tutorial, followed instructions to the letter, Applied "Bless" to 2 targets after editing the macro as shown in the tutorial and no status effect icon is applied.

**Expected behavior**
Status effect icon application

**Screenshots**

**Environment Info (please complete the following information):**
 Latest version of Foundry, DND5e, and CUB
![Screenshot 2022-06-26 005356](https://user-images.githubusercontent.com/15239231/175799954-2a5cd906-6d00-4c31-945e-dc2e79a3b66a.png)
![Screenshot 2022-06-26 005452](https://user-images.githubusercontent.com/15239231/175799980-1afc2a4b-3c05-47d7-a356-8ed9e5a7509c.png)
![Screenshot 2022-06-26 005518](https://user-images.githubusercontent.com/15239231/175799995-808c11ef-0660-46eb-b59b-6abae8ad23c3.png)
![Screenshot 2022-06-26 005712](https://user-images.githubusercontent.com/15239231/175800058-ec2710f3-20ae-4f19-90ed-87a8787c4788.png)
![Screenshot 2022-06-26 005754](https://user-images.githubusercontent.com/15239231/175800060-1598f6da-5a9f-4b88-b659-729289fa18ec.png)

**Additional context**

**Comment by Vrelvel** [comment]
![Screenshot 2022-06-26 010558](https://user-images.githubusercontent.com/15239231/175800223-147d0ea4-eda0-4a5a-a5c3-22886d06851e.png)
Because I forgot to upload it, here is a screenshot to verify my settings.

**Comment by eclarke12** [comment]
The command to add conditions is now `addCondition`. Sorry for any inconvenience.
