### ISSUE TITLE
Changes in Condition Lab not visible in Token HUD when Dfreds Convenient Effects is enabled

### ISSUE THREAD

**Issue by CaosFR** [death-save/combat-utility-belt#701]
Hi,
Before describe my bug, thanks for your module. It's one of the best module for foundry :).

**Describe the bug**
Imported mappings are not save in Token HUD when I refresh the game.

**To Reproduce**
1. Go to 'Condition Lab', import a JSON File and save the mapping.
2. Refresh the game (F5, disable a module, exit the game...)
3. The imported configuration is keep in the Condition Lab (Other/Imported) but is not working. Conditions are not visible in the Token HUD.
4. On each refresh I have to back to "System - Default" mapping, save, and re-import the same file and save. 

**Expected behavior**
I would like to keep and save the imported mappings as default.

**Screenshots**
![capture](https://user-images.githubusercontent.com/37581932/187253782-232a59a1-3ac7-40de-b3d1-8b033cb9feb7.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 9.269
 - Game System / Version: DnD5e / 1.6.3
 - CUB Version : 1.911
 - Browser Chromium Version 104.0.5112.102
 - OS : Windows 10 21H2

**Additional context**
[cub-dnd5e-condition-map.zip](https://github.com/death-save/combat-utility-belt/files/9446464/cub-dnd5e-condition-map.zip)

Thanks for your help

**Comment by eclarke12** [comment]
Please try disabling other modules and see if the issue persists.

**Comment by CaosFR** [comment]
Yes thanks !
When I disable "DFreds Convenient Effects" the problem is solve. Do you know how I can active both of the them ?

**Comment by eclarke12** [comment]
Dfreds Convenient Effects and CUB Enhanced Conditions are incompatible as they both attempt to manipulate the status effects.

**Comment by CaosFR** [comment]
Yes, I have chage the "Modify Status Effect" on "Nothing" to "Add" and back to "Nothing". It's clear now.

**Comment by eclarke12** [comment]
Sorry I could not help more.

**Comment by CaosFR** [comment]
It's perfect, dont worry.
