### ISSUE TITLE
Invisibility not working with new settings

### ISSUE THREAD

**Issue by etoy22** [death-save/combat-utility-belt#704]
**Describe the bug**
The invisibility condition given by this module is currently not making the creature invisible as per the foundry vtt v10 update. 

**To Reproduce**

**Expected behavior**
Make the creature invisible as the base foundry does

**Screenshots**
Base Foundry
![image](https://user-images.githubusercontent.com/20910516/188023806-70333b06-03e6-472b-9e48-47689ea97096.png)

Module:
![image](https://user-images.githubusercontent.com/20910516/188023841-f1d66b47-22f6-40ae-bee5-c12f08cfd98c.png)

**Environment Info (please complete the following information):**
 - Foundry Version: V10 - Build 284
 - Game System / Version: dnd5e 2.02
 - CUB Version 1.10.1
 - Browser: Foundry Application
 - OS: Windows 11
**Additional context**

**Comment by BangBengBongBung** [comment]
The same problem with the Blind condition, effect of Base Foundry does not apply to the effect of the module.

**Comment by strongpauly** [comment]
My simple PR will fix this issue, but only when the removeDefaultFlags setting is true.

Foundry only allows a single effect to be "Invisible" or "Blinded".  Adding multiple would require more work.
