### ISSUE TITLE
dnd5e-extended.json Import Fails

### ISSUE THREAD

**Issue by imobe001** [death-save/combat-utility-belt#707]
Not sure what is going on, but your extended conditions json does not import properly with the most recent version of foundry and combat utility belt.

As an example, I tried to import it and save the mapping, the bless condition didn't show up anywhere in "Default" or "Other/Imported".

Error in the console:
Uncaught (in promise) SyntaxError: Unexpected token '<', "

<!DOCTYPE "... is not valid JSON
[Detected 1 package: combat-utility-belt]
    at JSON.parse (<anonymous>)
    at ConditionLab._processImport (condition-lab.js:380:27)

**Comment by eclarke12** [comment]
This should be fixed when v1.10.2 is released
