### ISSUE TITLE
Hide Names causing actor sheet title bar gets additional "name" buttons added when making changes to sheet

### ISSUE THREAD

**Issue by damccull** [death-save/combat-utility-belt#708]
**Describe the bug**
When Name Hider is enabled as in this photo it causes multile copies of a sheet's name to appear in the title bar as clickable buttons when any change is made to the sheet.

**To Reproduce**
1. Enable name hider as in the screenshot
2. Open an actor sheet for a hostile actor
3. Make any change
4. See a new name button pop up'

**Expected behavior**
No new named buttons should be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/401104/189037604-aa07b495-10d8-4514-854f-03f2dec08092.png)
![image](https://user-images.githubusercontent.com/401104/189037869-0e20021f-d04b-4857-b3df-62ae9cc95765.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 10.248
 - Game System / Version: dnd5e 2.0.2
 - CUB Version: 1.10.1
 - Browser: Chromium-based Microsoft Edge Version 105.0.1343.27 (Official build) (64-bit)
 - OS: Windows 10.0.19044

**Comment by eclarke12** [comment]
I am unable to replicate this in Foundry v10.285. It looks like you might have some other kind of UI module/custom sheet as the buttons in the title bar look non-standard. Please try disabling other modules and test with only CUB enabled.

**Comment by damccull** [comment]
Ok I'll try it today.

**Comment by damccull** [comment]
So i used Find the Culprit to disable everything except CUB and FTC and I'm still getting it. I open a player actor sheet in dnd5e and click Inspiration checkbox a few times and they show up. Anything else I can look at? More info I can provide? Is there a debug log somewhere you'd like?

![image](https://user-images.githubusercontent.com/401104/189660615-b777ca06-c734-4f39-a6d6-8265c5667351.png)

**Comment by eduardopato41** [comment]
This is happening on my game as well. I tried disabling CUB and that fix it but I really like this feature 😞

**Comment by eclarke12** [comment]
> So i used Find the Culprit to disable everything except CUB and FTC and I'm still getting it. I open a player actor sheet in dnd5e and click Inspiration checkbox a few times and they show up. Anything else I can look at? More info I can provide? Is there a debug log somewhere you'd like?
> 
> ![image](https://user-images.githubusercontent.com/401104/189660615-b777ca06-c734-4f39-a6d6-8265c5667351.png)

Are you still on Foundry v10.248? If so, please update to v10.285 and let me know if it's still occurring thanks!

**Comment by eclarke12** [comment]
> This is happening on my game as well. I tried disabling CUB and that fix it but I really like this feature 😞

You should only need to disable the Hide Names functionality to fix this in your world.

**Comment by eduardopato41** [comment]
> > This is happening on my game as well. I tried disabling CUB and that fix it but I really like this feature 😞
> 
> You should only need to disable the Hide Names functionality to fix this in your world.

And I know that I can disabled just the Hide Names feature but I've been using CUB for this feature and Concentrator. And I rather have the buggy header than not have this on haha
I was just hoping to reiterate @damccull 's problem since there was already a issue open about this.

Oh, and I know you asked op but I'm running the lastest version (10.285) of Foundry and I'm still getting duplicates.
![image](https://user-images.githubusercontent.com/73562608/190019554-950fdca0-49dc-4808-8751-2ffc59dfc5ab.png)

Thanks!

**Comment by damccull** [comment]
Yes, sorry, should have mentioned I updated to 285 and still have the issue. Glad you were able to reproduce it. Looking forward to the fix.

> > So i used Find the Culprit to disable everything except CUB and FTC and I'm still getting it. I open a player actor sheet in dnd5e and click Inspiration checkbox a few times and they show up. Anything else I can look at? More info I can provide? Is there a debug log somewhere you'd like?
> > 
> > ![image](https://user-images.githubusercontent.com/401104/189660615-b777ca06-c734-4f39-a6d6-8265c5667351.png)
> 
> Are you still on Foundry v10.248? If so, please update to v10.285 and let me know if it's still occurring thanks!

**Comment by jarodun** [comment]
This happends in pf1e as well

**Comment by 9ryex5** [comment]
I have the same problem, using v10 build 287
