### ISSUE TITLE
Can't open Hide Names config from Actor Sheet

### ISSUE THREAD

**Issue by CepheiA2** [death-save/combat-utility-belt#723]
**Describe the bug**
Hide Actor Names Feature doesn't work, the icon appear on the actor sheet but i cannot interact with it.

**Environment Info (please complete the following information):**
 - Foundry Version: V10
 - Game System: DnD 5e 2.0.3
 - CUB Version 1.10.3
 - Browser Chrome
 - Windows 10

**Comment by nschoenwald** [comment]
I have the same issue. Hiding the actor names works, but you can't open the menu from an actor's sheet.
It does seem possible to open it from a token's sheet, but then it only unhides the name for that specific token instance of the actor, whereas I want to unhide all tokens created from an actor.

**Comment by KingTiki** [comment]
Having the same issue

**Comment by Almarane** [comment]
Same here, seems like it comes from the Default Disposition : 
```
foundry.js:747 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
[Detected 1 package: combat-utility-belt]
    at HideNPCNamesActorForm.getData (actor-form.js:34)
    at HideNPCNamesActorForm._render (foundry.js:5067)
    at HideNPCNamesActorForm._render (foundry.js:5780)
    at HideNPCNamesActorForm.render (foundry.js:5026)
    at HTMLAnchorElement.<anonymous> (hide-npc-names.js:87)
```
    
    actor-form.js:34 refers to :
`const dispositionIcon = DEFAULT_CONFIG.hideNames[`${disposition.toLowerCase()}Icon`];`

**Comment by lyao6104** [comment]
Line 32 of `actor-form.js` has `const dispositionEnum = actor?.token?.disposition ?? actor?.token?.disposition;`

I tried replacing the `token?` on the right side with `prototypeToken?` locally and it seems to fix the issue on my end. I haven't tested it much though.

**Comment by nschoenwald** [comment]
This fix works for me as well, and I haven't noticed any issues after playing around with it for a while.

**Comment by M0nk3yy** [comment]
Fix seemed to work for me, thank you lyao

**Comment by eclarke12** [comment]
I'll try to review the suggestion from @lyao6104 and put out a fix in the next few days.
