### ISSUE TITLE
Hud Gone

### ISSUE THREAD

**Issue by SplashCity46** [death-save/combat-utility-belt#744]
**Describe the bug**
My hud is gone. I updated with the new 5e update and it is no longer there.

**To Reproduce**
Login with the newest 5e update.

**Expected behavior**

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 10 - Build 291
 - Game System / Version: dnd5e 2.2.1
 - CUB Version: 1.10.4
 - Browser: Chrome
 - OS: Windows 10

**Additional context**

**Comment by eclarke12** [comment]
Support for CUB has ended. In the future another dev may pick it up, or you can investigate other modules with similar functions.
