### ISSUE TITLE
Enhanced Condition icons not updating 

### ISSUE THREAD

**Issue by Jesiir** [death-save/combat-utility-belt#747]
Hey 
I've read about how death-save probably wont continue updating this mod because of how overwhelming it is. But maybe someone can help me with this little issue. 
I never worked with CUB before and just updated to version 12 of Foundry and version 4.x of DnD 5e. I want to use the Concentration and Enhanced Condition Tools brought by this mod. 
I want to change Icons of custom Conditions - That works. I am able to change it but it only changes in the Edit Tab of the Condition (I tried it with custom and build in icons - neither work). 

**Problems with the Icons not updating**
![image](https://github.com/user-attachments/assets/15d26c3a-9ffd-4d89-b960-f099a7a49118)
![image](https://github.com/user-attachments/assets/4914acc4-59ee-4823-a021-574e0e17fe08)

 - Foundry Version: 12.3.3.1
 - Game System / Version: DnD5e
 - CUB Version latest
 - Browser chrome
 - OS Windows 10

**Comment by eclarke12** [comment]
The data models of Foundry and dnd5e are probably too far removed from what CUB is expecting. Unfortunately I don't think this will work. Please look at other mods to provide this functionality.
