### ISSUE TITLE
[BUG] Enhanced Conditions - chat output duplicates itself for every trusted+ user

### ISSUE THREAD

**Issue by Mnemonicide** [death-save/combat-utility-belt#91]
https://discordapp.com/channels/170995199584108546/513918036919713802/686084010656792576

**Comment by Mnemonicide** [comment]
It happens when "injured" enhanced status is set automatically
I've also added injured status marker's SVG to condition lab, if that matters

To reproduce:
0) Open DM view (used electron app), open a trusted player's view in another browser (used chromium)
1) [optional] Activate any scene, so both DM and player are on the same scene
2) Change PC's token hp to less than half hp
2) Injured message duplicates
If PC is injured, concentration messages are also duplicated

**Comment by eclarke12** [comment]
Replicated the issue in dev environment. The issue is occurring because of some recursion between marking the token as a injured and firing the chat message creation. Need to think about best way to solve.

What is really needed is a refactor to bring Mark Injured/Dead into Enhanced conditions.
