### ISSUE TITLE
Token Starting Location

### ISSUE THREAD

**Issue by Genkitty** [death-save/combat-utility-belt#96]
At the start of each token's turn, place a marker of some sort where the token is and leave it there while the token moves around.  At the start of the next token's turn, move the marker to the starting location for the next token.  

Bonus points for per-actor customizing of the marker :)

**Comment by eclarke12** [comment]
Similar to #102

**Comment by Genkitty** [comment]
'Similar' insofar as it deals with token movement. :P :)

**Comment by eclarke12** [comment]
@Genkitty Sorry to say this is out of scope for CUB for the foreseeable future, but I believe there are modules that track/restrict token movement that might fulfill this.
